#!/usr/bin/env bash
# Benchmark TB-IR split emission across `--emit-jobs` values.
#
# Measures the frontend only (`--emit-only`), so nothing here depends on
# Verilator. Reports the per-phase numbers harc prints plus total wall
# time, and repeats each configuration so the noise is visible rather than
# averaged away.
#
# Usage:
#   bench/split_emit/run_bench.sh [workdir] [group_size] [reps]
#
# Build the release binary first: `cargo build --release`.
set -euo pipefail

WORKDIR="${1:-/tmp/harc_split_emit_bench}"
GROUP_SIZE="${2:-}"
REPS="${3:-3}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HARC="$REPO_ROOT/target/release/harc"

if [[ ! -x "$HARC" ]]; then
  echo "error: $HARC not found; run 'cargo build --release' first" >&2
  exit 1
fi

if [[ ! -f "$WORKDIR/suite.harc" ]]; then
  echo "generating suite in $WORKDIR"
  python3 "$REPO_ROOT/bench/split_emit/gen_suite.py" --outdir "$WORKDIR"
fi

# M0: default to all three group sizes when not specified
if [[ -z "$GROUP_SIZE" ]]; then
  GROUP_SIZES=(1 4 32)
else
  GROUP_SIZES=("$GROUP_SIZE")
fi

echo "harc:       $HARC"
echo "suite:      $WORKDIR/suite.harc"
echo "group sizes: ${GROUP_SIZES[*]}"
cpu_count=""
if command -v nproc >/dev/null 2>&1; then
  cpu_count=$(nproc 2>/dev/null || true)
fi
if [[ -z "$cpu_count" ]] && command -v sysctl >/dev/null 2>&1; then
  cpu_count=$(sysctl -n hw.ncpu 2>/dev/null || true)
fi
if [[ -z "$cpu_count" ]] && command -v getconf >/dev/null 2>&1; then
  cpu_count=$(getconf _NPROCESSORS_ONLN 2>/dev/null || true)
fi
cpu_count=${cpu_count:-unknown}
echo "cpus:       $cpu_count"
echo

# Checked, portable single replacement for incremental-edit probes. BSD sed
# accepts some GNU address forms without changing the file, which can turn a
# purported edit into a silent no-op and invalidate the reuse measurement.
replace_once() {
  local path="$1" old="$2" new="$3"
  python3 -c 'from pathlib import Path; import sys; p = Path(sys.argv[1]); s = p.read_text(); old, new = sys.argv[2:4]; assert old in s, f"pattern not found: {old}"; p.write_text(s.replace(old, new, 1))' "$path" "$old" "$new"
}

# Helper to report generated bytes by category for a given outdir
report_bytes() {
  local outdir="$1"
  local label="$2"
  if [[ ! -d "$outdir" ]]; then
    echo "$label: no outdir"
    return
  fi
  echo "=== $label byte breakdown ==="
  while IFS= read -r -d '' f; do
    printf "  %8s  %s\n" "$(du -h "$f" | cut -f1)" "$(basename "$f")"
  done < <(find "$outdir" -maxdepth 1 -type f \( -name '*.hpp' -o -name '*.cpp' \) -print0)
  if command -v du >/dev/null 2>&1; then
    total=$(du -sh "$outdir" 2>/dev/null | cut -f1)
    echo "  total $total  ($outdir)"
  fi
  # Native object sizes if Verilator build was run
  if [[ -d "$outdir/obj_dir" ]]; then
    echo "  -- obj_dir --"
    du -sh "$outdir/obj_dir" 2>/dev/null | sed 's/^/  /'
    ls -lh "$outdir/obj_dir"/*.o 2>/dev/null | awk '{printf "  %8s  %s\n", $5, $9}' | head -20
  fi
}

for GROUP_SIZE in "${GROUP_SIZES[@]}"; do
echo "===== group size $GROUP_SIZE ====="
for jobs in 1 2 4; do
  for rep in $(seq 1 "$REPS"); do
    out="$WORKDIR/out_j${jobs}_g${GROUP_SIZE}"
    # Clean between reps: an unchanged rerun skips every write, which
    # measures a different thing (see README).
    rm -rf "$out"
    start_ns=$(python3 -c 'import time; print(time.perf_counter_ns())')
    log=$("$HARC" sim "$WORKDIR/suite.harc" \
      --sv "$WORKDIR/SplitAdder.sv" \
      --top SplitAdder \
      --codegen tbir \
      --cpp-split tests \
      --cpp-split-group-size "$GROUP_SIZE" \
      --emit-only \
      --outdir "$out" \
      --emit-jobs "$jobs" 2>&1)
    end_ns=$(python3 -c 'import time; print(time.perf_counter_ns())')
    total=$(awk "BEGIN { printf \"%.3f\", ($end_ns - $start_ns) / 1000000000 }")
    parse=$(sed -n 's/^TBIR parse: \(.*\) | merge: .*/\1/p' <<<"$log")
    lower=$(sed -n 's/^TBIR lower: \(.*\) | verify: .*/\1/p' <<<"$log")
    plan=$(sed -n 's/^TBIR split plan: .*, planned in //p' <<<"$log")
    emit=$(sed -n 's/^TBIR split emit: .*, //p' <<<"$log")
    echo "jobs=$jobs rep=$rep  total=${total}s  parse=${parse}  lower=${lower}  plan=${plan}  emit=${emit}"
  done
done

echo
echo "--- self-contained byte breakdown (group $GROUP_SIZE) ---"
report_bytes "$WORKDIR/out_j4_g${GROUP_SIZE}" "self-contained g$GROUP_SIZE"

# M0: Separate layout for same group size — measures shared vs test-owned
echo
echo "--- separate layout (group $GROUP_SIZE, jobs=4) ---"
out_sep="$WORKDIR/out_sep_g${GROUP_SIZE}"
rm -rf "$out_sep"
log_sep=$("$HARC" sim "$WORKDIR/suite.harc" \
  --sv "$WORKDIR/SplitAdder.sv" \
  --top SplitAdder \
  --codegen tbir \
  --cpp-split tests \
  --cpp-split-layout common \
  --cpp-split-group-size "$GROUP_SIZE" \
  --emit-only \
  --outdir "$out_sep" \
  --emit-jobs 4 2>&1)
echo "$log_sep" | grep -E "TBIR category|TBIR layout|TBIR separate"
report_bytes "$out_sep" "separate g$GROUP_SIZE"

# Native compile metrics if Verilator is available (M0)
if command -v verilator >/dev/null 2>&1; then
  echo
  echo "native compile (Verilator) for g$GROUP_SIZE separate vs self-contained:"
  for layout in "self-contained:$WORKDIR/out_j4_g${GROUP_SIZE}" "separate:$out_sep"; do
    IFS=: read -r lname ldir <<<"$layout"
    if [[ "$lname" == "separate" ]]; then
      layout_arg="--cpp-split-layout common"
    else
      layout_arg=""
    fi
    # Full build wall time and CPU via /usr/bin/time if available
    if command -v /usr/bin/time >/dev/null 2>&1; then
      echo "  $lname: timing via /usr/bin/time -p"
      # shellcheck disable=SC2086
      /usr/bin/time -p "$HARC" sim "$WORKDIR/suite.harc" --sv "$WORKDIR/SplitAdder.sv" --top SplitAdder --codegen tbir --cpp-split tests $layout_arg --cpp-split-group-size "$GROUP_SIZE" --outdir "$ldir" 2>&1 | grep -E "real|user|sys" | sed 's/^/    /'
    else
      echo "  $lname: /usr/bin/time not found, skipping CPU timing"
    fi
  done
fi

# Incremental rebuilds (M0): no-op, test-only edit, shared-body edit, shared-interface edit
echo
echo "incremental rebuilds for g$GROUP_SIZE (separate layout):"
# no-op rerun — should reuse everything
"$HARC" sim "$WORKDIR/suite.harc" --sv "$WORKDIR/SplitAdder.sv" --top SplitAdder --codegen tbir --cpp-split tests --cpp-split-layout common --cpp-split-group-size "$GROUP_SIZE" --emit-only --outdir "$out_sep" --emit-jobs 4 2>&1 | grep -E "emitted|reused" | head -10 | sed 's/^/  no-op: /'
# test-only edit: change one test's body (affects exactly one shard)
cp "$WORKDIR/suite.harc" "$WORKDIR/suite.harc.bak"
# Change B0's assert value (tag 0 -> 1) — touches only shard 1.
replace_once "$WORKDIR/suite.harc" "        assert r.tag == 0" "        assert r.tag == 1"
"$HARC" sim "$WORKDIR/suite.harc" --sv "$WORKDIR/SplitAdder.sv" --top SplitAdder --codegen tbir --cpp-split tests --cpp-split-layout common --cpp-split-group-size "$GROUP_SIZE" --emit-only --outdir "$out_sep" --emit-jobs 4 2>&1 | grep -E "emitted|reused" | head -10 | sed 's/^/  test-edit (one shard): /'
mv "$WORKDIR/suite.harc.bak" "$WORKDIR/suite.harc"
# Restore the output baseline too: the test edit changed shard 1 on disk, and
# otherwise the following shared-body measurement would include reverting that
# shard alongside its intended common.cpp-only change.
"$HARC" sim "$WORKDIR/suite.harc" --sv "$WORKDIR/SplitAdder.sv" --top SplitAdder --codegen tbir --cpp-split tests --cpp-split-layout common --cpp-split-group-size "$GROUP_SIZE" --emit-only --outdir "$out_sep" --emit-jobs 4 >/dev/null 2>&1
# shared-body edit: change the reusable-testbench lifecycle implementation.
# Under the common layout this must affect common.cpp only; every test shard
# keeps calling the same external lifecycle symbol and should be reused.
cp "$WORKDIR/suite.harc" "$WORKDIR/suite.harc.bak"
replace_once "$WORKDIR/suite.harc" "shared lifecycle benchmark body v1" "shared lifecycle benchmark body v2"
"$HARC" sim "$WORKDIR/suite.harc" --sv "$WORKDIR/SplitAdder.sv" --top SplitAdder --codegen tbir --cpp-split tests --cpp-split-layout common --cpp-split-group-size "$GROUP_SIZE" --emit-only --outdir "$out_sep" --emit-jobs 4 2>&1 | grep -E "emitted|reused" | head -10 | sed 's/^/  shared-body: /'
mv "$WORKDIR/suite.harc.bak" "$WORKDIR/suite.harc"
# shared-interface edit: change a record field type layout (affects interface + dependent shards)
cp "$WORKDIR/suite.harc" "$WORKDIR/suite.harc.bak"
replace_once "$WORKDIR/suite.harc" "addr : uint<32>" "addr : uint<16>"
"$HARC" sim "$WORKDIR/suite.harc" --sv "$WORKDIR/SplitAdder.sv" --top SplitAdder --codegen tbir --cpp-split tests --cpp-split-layout common --cpp-split-group-size "$GROUP_SIZE" --emit-only --outdir "$out_sep" --emit-jobs 4 2>&1 | grep -E "emitted|reused" | head -10 | sed 's/^/  shared-iface: /'
mv "$WORKDIR/suite.harc.bak" "$WORKDIR/suite.harc"
done

echo
echo "unchanged rerun at jobs=4 (read+compare, no writes) — isolates write I/O:"
for rep in $(seq 1 "$REPS"); do
  # Use last GROUP_SIZE from loop
  last_index=$((${#GROUP_SIZES[@]} - 1))
  last_g="${GROUP_SIZES[$last_index]}"
  "$HARC" sim "$WORKDIR/suite.harc" \
    --sv "$WORKDIR/SplitAdder.sv" \
    --top SplitAdder \
    --codegen tbir \
    --cpp-split tests \
    --cpp-split-group-size "$last_g" \
    --emit-only \
    --outdir "$WORKDIR/out_j4_g${last_g}" \
    --emit-jobs 4 2>&1 | sed -n 's/^TBIR split emit: /  /p'
done
