//! Fixed C++ scaffolding for the TB-IR backend. Every block of text
//! here mirrors the live v1 (`cpp_tb`) emission contract byte-for-byte
//! where the output is runtime-observable (trace events, log lines,
//! clock scheduling), so the v1-vs-tbir equivalence gate can diff
//! normalized semantic traces.

use crate::ir::ClockSpec;
use std::fmt::Write as _;

pub(super) const INDENT: &str = "    ";

/// File preamble: includes, trace gates, eval helpers, RNG.
///
/// `problem_table_cpp` is the rendered constraint-solver runtime problem
/// table (`RuntimeProblemTable::render_cpp_table`) when the program has
/// a cataloged randomize site, else empty. `uses_constraint_solver`
/// independently gates the Z3 runtime include because component-scope
/// randomize sites are not members of that table.
pub(super) fn preamble(
    out: &mut String,
    dut_type: &str,
    test_names: &[String],
    problem_table_cpp: &str,
    uses_constraint_solver: bool,
    has_probes: bool,
    cosim: Option<&crate::codegen::cpp_tb::CosimOpts>,
) {
    writeln!(out, "// Auto-generated by harc — do not edit.").ok();
    writeln!(out, "// Codegen: tbir (TB-IR loop-switch backend).").ok();
    writeln!(out, "// HARC test: {}", test_names.join(", ")).ok();
    out.push_str("\n#ifdef __clang__\n#pragma clang optimize off\n#endif\n\n");
    if cosim.is_none() {
        writeln!(out, "#include \"V{dut_type}.h\"").ok();
    }
    // Probe access dereferences `dut->rootp->...`; the `rootp` member is
    // only forward-declared in `V<Top>.h`, so pull in the root struct's
    // full definition. Gated on probe use (mirrors v1's
    // `aggregated_probes` include gate). See docs/probe-signals.md.
    // In co-sim mode the shim provides its own `rootp` of probe
    // accessor proxies — no Verilated root header exists to include.
    if has_probes && cosim.is_none() {
        writeln!(out, "#include \"V{dut_type}___024root.h\"").ok();
    }
    out.push_str(
        r#"#include "verilated.h"
#if VM_COVERAGE
#include "verilated_cov.h"
#endif
#if defined(HARC_TRACE_VCD)
#include "verilated_vcd_c.h"
#define HARC_TRACE_ENABLED 1
using HarcTraceC = VerilatedVcdC;
#elif defined(HARC_TRACE_FST)
#include "verilated_fst_c.h"
#define HARC_TRACE_ENABLED 1
using HarcTraceC = VerilatedFstC;
#else
#define HARC_TRACE_ENABLED 0
#endif
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstdarg>
#include <cstring>
#include <string>
#include <array>
#include <vector>
#include <deque>
#include <functional>
#include <thread>
#include <atomic>
#include "harc_thread_rt.h"
#include "harc_random_rt.h"
#include "harc_queue_rt.h"
#include "harc_trace_rt.h"
#include "harc_log_rt.h"
"#,
    );
    if let Some(co) = cosim {
        out.push_str("#include \"harc_cosim_rt.h\"\n");
        cosim_dut_shim(out, dut_type, co);
    }
    // Constraint-solver runtime: the Z3 helper header + the per-program
    // problem table, emitted only when a randomize site exists (v1's
    // `uses_constraint_solver` gate). Without a site, the generated TB
    // never links Z3 — same as v1.
    if uses_constraint_solver {
        writeln!(
            out,
            "#include \"harc_z3_rt.h\"   // randomize(t) with <constraints>"
        )
        .ok();
    }
    if cosim.is_some() {
        // Bridge-aware edge helpers: same call sites as the direct
        // templates, but each edge advances real simulator time through
        // the co-sim bridge (advance to the nominal edge, write the
        // clock through the DPI setter, settle 1 ps so FF/comb updates
        // land). Because these are plain blocking calls they work from
        // ANY emission context — the drive loop, helper functions with
        // `wait`, and the synchronous `tick()` paths blocking TLM/bus
        // calls lower to.
        out.push_str(
            r#"
template<typename DUT>
static void _harc_eval_negedge(DUT* dut) {
    harc_rt::cosim::bridge().advance_to_next_edge();
    if constexpr (requires { dut->clk; }) { dut->clk = 0; }
    harc_rt::cosim::bridge().settle();
}
template<typename DUT>
static void _harc_eval_posedge(DUT* dut) {
    harc_rt::cosim::bridge().advance_to_next_edge();
    if constexpr (requires { dut->clk; }) { dut->clk = 1; }
    harc_rt::cosim::bridge().settle();
}

"#,
        );
    } else {
        out.push_str(
            r#"
template<typename DUT>
static void _harc_eval_negedge(DUT* dut) {
    if constexpr (requires { dut->clk; }) { dut->clk = 0; }
    dut->eval();
}
template<typename DUT>
static void _harc_eval_posedge(DUT* dut) {
    if constexpr (requires { dut->clk; }) { dut->clk = 1; }
    dut->eval();
}

"#,
        );
    }
    out.push_str(problem_table_cpp);
    out.push_str(
        r#"static harc_rt::random::HarcRng harc_rng;
static inline uint64_t harc_rng_next() {
    return harc_rng.next();
}

"#,
    );
}

/// Co-sim DUT shim (`--cosim dpi`). Takes the place of the Verilated
/// `V<Top>` class in the emitted TB: same type name, same member names,
/// so every `dut-><port>` access site the direct backend emits compiles
/// unchanged — but each member is an id-keyed `SigProxy` forwarding to
/// the DPI-exported accessors of the generated `HarcCosimTop.sv`
/// harness. `eval()` maps to a 1 ps bridge settle so mid-cycle drive
/// points get a real simulator time step to re-settle combinational
/// logic.
///
/// Ports wider than 64 bits get a word-indexed `WideSigProxy` backed by
/// the word-granular accessor exports.
fn cosim_dut_shim(out: &mut String, dut_type: &str, co: &crate::codegen::cpp_tb::CosimOpts) {
    writeln!(out).ok();
    writeln!(
        out,
        "// Co-sim DUT shim for `{dut_type}` — id table mirrors the generated"
    )
    .ok();
    writeln!(out, "// HarcCosimTop.sv accessor case tables.").ok();
    writeln!(out, "struct V{dut_type} {{").ok();
    for (id, p) in co.ports.iter().enumerate() {
        if let Some(n) = p.unpacked_elems {
            // Unpacked-array port: element-indexed proxy; raw-subscript
            // access sites (`dut->p[i]`) go through the element
            // accessors.
            writeln!(
                out,
                "{INDENT}harc_rt::cosim::UnpackedSigProxy<{id}, {n}> {};",
                p.name
            )
            .ok();
            continue;
        }
        if p.width_bits > 64 {
            // Wide port: word-indexed proxy shaped like VlWide<N> (the
            // wide helpers derive the word count from sizeof).
            let words = p.width_bits.div_ceil(32);
            writeln!(
                out,
                "{INDENT}harc_rt::cosim::WideSigProxy<{id}, {words}> {};",
                p.name
            )
            .ok();
            continue;
        }
        writeln!(out, "{INDENT}harc_rt::cosim::SigProxy<{id}> {};", p.name).ok();
    }
    // Probe accessors: the emission reads probes as
    // `dut->rootp-><Verilator-mangled name>` (and writes the `_drv` /
    // `_en` siblings for force probes) — provide a `rootp` whose members
    // carry exactly those names, backed by accessor proxies keyed to the
    // harness's hierarchical references into the bound probe stub.
    if !co.probes.is_empty() {
        writeln!(out, "{INDENT}struct _HarcCosimRoot {{").ok();
        for (probe, (read_id, force_ids)) in co.probes.iter().zip(co.probe_ids()) {
            let mangled = crate::codegen::sv_stub::mangled_accessor(dut_type, &probe.name);
            writeln!(
                out,
                "{INDENT}{INDENT}harc_rt::cosim::SigProxy<{read_id}> {mangled};"
            )
            .ok();
            if let Some((drv_id, en_id)) = force_ids {
                writeln!(
                    out,
                    "{INDENT}{INDENT}harc_rt::cosim::SigProxy<{drv_id}> {mangled}_drv;"
                )
                .ok();
                writeln!(
                    out,
                    "{INDENT}{INDENT}harc_rt::cosim::SigProxy<{en_id}> {mangled}_en;"
                )
                .ok();
            }
        }
        writeln!(out, "{INDENT}}};").ok();
        writeln!(out, "{INDENT}_HarcCosimRoot _harc_root;").ok();
        writeln!(out, "{INDENT}_HarcCosimRoot* rootp = &_harc_root;").ok();
    }
    // eval() maps to a 1 ps bridge settle: the direct backend calls it
    // after mid-cycle drives (post-eval services, blocking-call loops)
    // to re-settle combinational logic — under co-sim the simulator
    // needs a real time step to do the same.
    writeln!(
        out,
        "{INDENT}void eval() {{ harc_rt::cosim::bridge().settle(); }}"
    )
    .ok();
    writeln!(out, "{INDENT}void final() {{}}").ok();
    writeln!(out, "}};").ok();
    writeln!(out).ok();
}

/// One testbench struct (only for non-synthetic testbenches).
/// `cov_fields` are (field name, covergroup struct name) pairs in
/// declaration order, emitted after the DUT pointer — same member
/// layout as v1. `scalar_fields` are run/check-shared scalar members
/// (`expected : uint<32> default 0`), with v1's C-type mapping.
/// One scoreboard declaration → C++ struct (v1's `emit_scoreboard`
/// shape): scalar counters with their declared defaults, `queue<T>`
/// fields as `harc_rt::HarcQueue<T>` members, plus the activity-tracking
/// `_last_in/out_cycle` heartbeat stamps v1 always injects (read by
/// `<env>.quiesced(N)` when the board is an env sub-component).
/// One bound-to target-TLM responder instance: a test-scope local
/// struct (state fields + activity stamps) plus its instance, mirroring
/// v1's per-instance component struct. Declared inside the test function
/// so the run/check coroutine and the actor coroutines share it by `[&]`
/// reference. Emitted at one indent level (inside the test fn body).
pub(super) fn target_state_struct_inst(
    out: &mut String,
    schema: &crate::ir::TransactorSchema,
    instance: &str,
    records: &[crate::ir::RecordSchema],
) {
    let ty = format!("_{}_{}_state", schema.name, instance);
    writeln!(out, "{INDENT}struct {ty} {{").ok();
    emit_state_struct_body(out, schema, records, 2);
    writeln!(out, "{INDENT}}} {instance};").ok();
}

/// The shared per-TYPE state struct name for the state-receiver method
/// ABI (`_<Type>_state`). One such struct type serves every unbound
/// active/passive instance of the type; each instance is its own variable
/// of this type (`emit_unbound_state_var`), and the type-shared method
/// lambda takes it by reference as `self_state` so one body drives any
/// number of instances (#494 P1b).
pub(super) fn unbound_state_struct_ty(schema: &crate::ir::TransactorSchema) -> String {
    format!("_{}_state", schema.name)
}

/// Emit the shared per-TYPE state struct declaration for the state-receiver
/// ABI. Emitted once per transactor type that has at least one unbound
/// stateful instance in the test, before any instance variable or method
/// lambda that references it.
pub(super) fn unbound_state_struct_decl(
    out: &mut String,
    schema: &crate::ir::TransactorSchema,
    records: &[crate::ir::RecordSchema],
) {
    let ty = unbound_state_struct_ty(schema);
    writeln!(out, "{INDENT}struct {ty} {{").ok();
    emit_state_struct_body(out, schema, records, 2);
    writeln!(out, "{INDENT}}};").ok();
}

/// Emit one storage variable of the shared per-TYPE state struct. `storage`
/// may be a generated symbol distinct from the source instance name; this
/// prevents a demand-created heartbeat object from colliding with a method
/// lambda such as `<Type>_<method>`.
pub(super) fn unbound_state_var(
    out: &mut String,
    schema: &crate::ir::TransactorSchema,
    storage: &str,
) {
    let ty = unbound_state_struct_ty(schema);
    writeln!(out, "{INDENT}{ty} {storage};").ok();
}

/// The shared field layout of a per-instance transactor-state struct:
/// declared scalar/queue state fields with their defaults, plus the two
/// auto-injected activity-tracking heartbeat stamps.
fn emit_state_struct_body(
    out: &mut String,
    schema: &crate::ir::TransactorSchema,
    records: &[crate::ir::RecordSchema],
    depth: usize,
) {
    let pad = INDENT.repeat(depth);
    for f in &schema.state_fields {
        match &f.kind {
            crate::ir::StateFieldKind::Scalar { ty, default } => {
                let (cty, init) = scalar_field_decl(ty, *default);
                writeln!(out, "{pad}{cty} {} = {init};", f.name).ok();
            }
            crate::ir::StateFieldKind::Queue { elem } => {
                let elem = queue_elem_cty(elem, records);
                writeln!(out, "{pad}harc_rt::HarcQueue<{elem}> {};", f.name).ok();
            }
            // A whole value-record state member, carried by value (the
            // record struct is emitted earlier at file scope). Default-
            // constructed via the struct's own field initializers,
            // mirroring the scoreboard/component record-member shape.
            crate::ir::StateFieldKind::Record { record } => {
                let rname = &records[record.index()].name;
                writeln!(out, "{INDENT}{INDENT}{rname} {}{{}};", f.name).ok();
            }
        }
    }
    // Activity stamps, mirroring v1's auto-injected component fields
    // (`idle()`/`idle_in()`/`idle_out()` predicate backing).
    writeln!(out, "{pad}uint64_t _last_in_cycle = 0;").ok();
    writeln!(out, "{pad}uint64_t _last_out_cycle = 0;").ok();
}

/// C++ type and initializer for one declared scalar FIELD, shared by
/// the transactor-state, scoreboard, component, and testbench field
/// emitters. All four carried their own copy of a
/// `(bool | int64_t | uint64_t)` choice, which silently narrowed any
/// field wider than 64 bits to a 64-bit member; `field_scalar_cty` is
/// the same seam the queue-element emitter already uses, and it knows
/// about `_harc_u128` and `harc_rt::HarcWide<N>`.
fn scalar_field_decl(ty: &crate::ir::IrType, default: u64) -> (String, String) {
    match ty {
        crate::ir::IrType::Bool => (
            "bool".to_string(),
            if default != 0 { "true" } else { "false" }.to_string(),
        ),
        _ => (super::field_scalar_cty(ty), default.to_string()),
    }
}

/// The C++ element type for a `queue<T>` field. Scalars reuse the exact
/// width-aware local mapping; a value-record element is the record struct
/// (carried by value, matching v1's `HarcQueue<Rec>`).
fn queue_elem_cty(elem: &crate::ir::QueueElem, records: &[crate::ir::RecordSchema]) -> String {
    match elem {
        crate::ir::QueueElem::Scalar { ty } => super::field_scalar_cty(ty),
        crate::ir::QueueElem::FixedVec { elem, len } => super::field_scalar_cty(
            &crate::ir::IrType::FixedVec {
                elem: elem.clone(),
                len: *len,
            },
        ),
        crate::ir::QueueElem::List { elem } => {
            format!("std::vector<{}>", super::field_scalar_cty(elem))
        }
        crate::ir::QueueElem::Record(r) => records[r.index()].name.clone(),
    }
}

pub(super) fn scoreboard_struct(
    out: &mut String,
    sb: &crate::ir::ScoreboardSchema,
    records: &[crate::ir::RecordSchema],
) {
    writeln!(out, "struct {} {{", sb.name).ok();
    for f in &sb.fields {
        match &f.kind {
            crate::ir::ScoreboardFieldKind::Scalar { ty, default } => {
                // `main`'s `ScoreboardScalarDefault` carries a WIDE
                // literal, which the `u64` slot this branch documented
                // as a limitation cannot. Its representation wins here;
                // `scalar_field_decl` still serves the three emitters
                // whose schema default is still a `u64`.
                let init = match default {
                    crate::ir::ScoreboardScalarDefault::Narrow(value) => match ty {
                        crate::ir::IrType::Bool => {
                            if *value != 0 { "true" } else { "false" }.to_string()
                        }
                        _ => value.to_string(),
                    },
                    crate::ir::ScoreboardScalarDefault::Wide(words) => {
                        super::expr::wide_literal_cpp(words)
                    }
                };
                let cty = super::field_scalar_cty(ty);
                writeln!(out, "{INDENT}{cty} {} = {init};", f.name).ok();
            }
            crate::ir::ScoreboardFieldKind::Record { record } => {
                let cty = &records[record.index()].name;
                writeln!(out, "{INDENT}{cty} {}{{}};", f.name).ok();
            }
            crate::ir::ScoreboardFieldKind::List { elem, vec_len } => {
                let elem = super::field_scalar_cty(elem);
                let elem = match vec_len {
                    Some(len) => format!("std::array<{elem}, {len}>"),
                    None => elem,
                };
                writeln!(out, "{INDENT}std::vector<{elem}> {}{{}};", f.name).ok();
            }
            crate::ir::ScoreboardFieldKind::Queue { elem } => {
                let elem = queue_elem_cty(elem, records);
                writeln!(out, "{INDENT}harc_rt::HarcQueue<{elem}> {};", f.name).ok();
            }
        }
    }
    // Auto-injected activity-tracking stamps, matching v1's
    // `emit_scoreboard`. A data-only scoreboard counts as a component for
    // heartbeat purposes, so `<env>.quiesced(N)` (which expands to
    // `sb.idle(N)`) reads these stamps on a scoreboard sub-component.
    writeln!(out, "{INDENT}uint64_t _last_in_cycle = 0;").ok();
    writeln!(out, "{INDENT}uint64_t _last_out_cycle = 0;").ok();
    writeln!(out, "}};").ok();
    writeln!(out).ok();
}

/// The C++ payload type carried by an `event<T>` subscriber closure.
/// Mirrors v1's `payload_type_for_arg`: a scalar widens to
/// `uint64_t`/`int64_t`; a value-record payload is the record struct
/// (carried by value).
pub(super) fn event_payload_cty(
    p: &crate::ir::EventPayload,
    records: &[crate::ir::RecordSchema],
) -> String {
    match p {
        // The subscriber's parameter type. `field_scalar_cty` carries
        // the declared width; the pair this replaced could only say
        // 64 bits, so an `event<uint<1024>>` had nowhere to put the
        // other fifteen sixteenths.
        crate::ir::EventPayload::Scalar { .. } => {
            super::field_scalar_cty(&p.scalar_ir_type().expect("a scalar payload types"))
        }
        crate::ir::EventPayload::Record(r) => records[r.index()].name.clone(),
    }
}

/// One composite-component struct (env/agent cluster, flat-struct
/// subset). Mirrors v1's `emit_component_struct`: scalar/queue/event/
/// sub-component fields plus the `_last_in_cycle`/`_last_out_cycle`
/// heartbeat stamps. Sub-component fields are emitted by their component
/// name, so file order (subs before the env that holds them) guarantees
/// the held type is already defined.
pub(super) fn component_struct(
    out: &mut String,
    prog: &crate::ir::TbProgram,
    c: &crate::ir::ComponentSchema,
    components: &[crate::ir::ComponentSchema],
    scoreboards: &[crate::ir::ScoreboardSchema],
    records: &[crate::ir::RecordSchema],
) {
    use crate::ir::ComponentFieldKind;
    writeln!(out, "struct {} {{", c.name).ok();
    for f in &c.fields {
        match &f.kind {
            ComponentFieldKind::Scalar { ty, default } => {
                let (cty, init) = scalar_field_decl(ty, *default);
                writeln!(out, "{INDENT}{cty} {} = {init};", f.name).ok();
            }
            ComponentFieldKind::FixedVec(vec) => {
                // The fifth copy of the `(bool | int64_t | uint64_t)`
                // triple, and the last one. It would have rendered a
                // `Vec<uint<1024>, 4>` as `std::array<uint64_t, 4>` —
                // an array that compiles, runs, and keeps a
                // sixteenth of each element. v1 emits
                // `std::array<harc_rt::HarcWide<32>, 4>`, and
                // `field_scalar_cty` is the seam that says so.
                let cty = super::field_scalar_cty(&vec.elem);
                writeln!(
                    out,
                    "{INDENT}std::array<{cty}, {}> {}{{}};",
                    vec.len, f.name
                )
                .ok();
            }
            ComponentFieldKind::Record { record } => {
                let rname = &records[record.index()].name;
                writeln!(out, "{INDENT}{rname} {}{{}};", f.name).ok();
            }
            ComponentFieldKind::Queue { elem } => {
                let elem = queue_elem_cty(elem, records);
                writeln!(out, "{INDENT}harc_rt::HarcQueue<{elem}> {};", f.name).ok();
            }
            ComponentFieldKind::Event { payload } => {
                let pty = event_payload_cty(payload, records);
                writeln!(
                    out,
                    "{INDENT}std::vector<std::function<void({pty})>> {};",
                    f.name
                )
                .ok();
            }
            ComponentFieldKind::Sub { component, .. } => {
                let cname = &components[component.index()].name;
                writeln!(out, "{INDENT}{cname} {};", f.name).ok();
            }
            ComponentFieldKind::Dut { dut_type } => {
                // The DUT handle on an event-driven transactor: a Verilator
                // instance pointer the test binds (`drv.dut = dut`) and the
                // `on <ev>` handler pokes through. Matches v1's
                // `V<dut_type>* dut = nullptr;`.
                writeln!(out, "{INDENT}V{dut_type}* {} = nullptr;", f.name).ok();
            }
            ComponentFieldKind::ScoreboardSub { scoreboard } => {
                let sname = &scoreboards[scoreboard.index()].name;
                writeln!(out, "{INDENT}{sname} {};", f.name).ok();
            }
        }
    }
    for m in &c.methods {
        if m.cov_hook_subs.is_empty() {
            continue;
        }
        let arg_csv = component_method_param_ctypes(prog, m).join(", ");
        writeln!(
            out,
            "{INDENT}std::vector<std::function<void({arg_csv})>> _harc_cov_{}_pre;",
            m.name
        )
        .ok();
        writeln!(
            out,
            "{INDENT}std::vector<std::function<void({arg_csv})>> _harc_cov_{}_post;",
            m.name
        )
        .ok();
    }
    // v1's activity-tracking heartbeat stamps (read by idle predicates,
    // bumped on emit/in/out; carried for trace + future agent slice).
    writeln!(out, "{INDENT}uint64_t _last_in_cycle = 0;").ok();
    writeln!(out, "{INDENT}uint64_t _last_out_cycle = 0;").ok();
    writeln!(out, "}};").ok();
    writeln!(out).ok();
}

fn component_method_param_ctypes(
    prog: &crate::ir::TbProgram,
    m: &crate::ir::ComponentMethodSchema,
) -> Vec<String> {
    let func = prog.function(m.function);
    (0..m.param_names.len())
        .map(|i| match func.locals[i].ty {
            crate::ir::IrType::Record(r) => prog.records[r.index()].name.clone(),
            crate::ir::IrType::RecordSeq(r) => {
                format!("std::vector<{}>", prog.records[r.index()].name)
            }
            crate::ir::IrType::Seq(ref scalar) => {
                format!("std::vector<{}>", super::field_scalar_cty(scalar))
            }
            crate::ir::IrType::Component(c) => prog.components[c.index()].name.clone(),
            ref ty => super::local_scalar_cty(ty),
        })
        .collect()
}

pub(super) fn tb_struct(
    out: &mut String,
    tb_name: &str,
    dut_type: &str,
    cov_fields: &[(String, String)],
    state_fields: &[crate::ir::TbStateFieldSchema],
    scoreboard_fields: &[(String, String)],
    records: &[crate::ir::RecordSchema],
) {
    writeln!(out, "struct {tb_name} {{").ok();
    writeln!(out, "{INDENT}V{dut_type}* dut = nullptr;").ok();
    for (field, cg_name) in cov_fields {
        writeln!(out, "{INDENT}{cg_name} {field};").ok();
    }
    for (field, sb_type) in scoreboard_fields {
        writeln!(out, "{INDENT}{sb_type} {field};").ok();
    }
    for field in state_fields {
        match field {
            crate::ir::TbStateFieldSchema::Scalar(f)
                if matches!(f.ty, crate::ir::IrType::FixedVec { .. }) =>
            {
                // Fixed-vector host field. Zero-filled brace-init on the
                // `std::array` member (`std::array<cty, N> mem{};`),
                // matching v1 — `scalar_field_decl`'s `= <init>` form has no
                // constructor `std::array` accepts, which is exactly why a
                // `default` on such a field is refused at lowering.
                writeln!(
                    out,
                    "{INDENT}{} {}{{}};",
                    super::field_scalar_cty(&f.ty),
                    f.name
                )
                .ok();
            }
            crate::ir::TbStateFieldSchema::Scalar(f) => {
                let (cty, init) = scalar_field_decl(&f.ty, f.default);
                writeln!(out, "{INDENT}{cty} {} = {init};", f.name).ok();
            }
            crate::ir::TbStateFieldSchema::Queue(f) => {
                let elem = queue_elem_cty(&f.elem, records);
                writeln!(out, "{INDENT}harc_rt::HarcQueue<{elem}> {};", f.name).ok();
            }
        }
    }
    writeln!(out, "{INDENT}uint64_t _last_in_cycle = 0;").ok();
    writeln!(out, "{INDENT}uint64_t _last_out_cycle = 0;").ok();
    writeln!(out, "}};").ok();
    writeln!(out).ok();
}

pub(super) fn context_struct(out: &mut String, dut_type: &str) {
    writeln!(out, "struct HarcTestContext {{").ok();
    writeln!(out, "{INDENT}V{dut_type}* dut = nullptr;").ok();
    out.push_str(
        r#"#if HARC_TRACE_ENABLED
    HarcTraceC* tfp = nullptr;
    std::string _wave_path;
#endif
    uint64_t _trace_time = 0;
    int errors = 0;
    bool _fatal = false;
    int cycle_count = 0;
    harc_rt::trace::HarcTraceWriter trace;
    harc_rt::log::HarcLogContext log_ctx;
    std::vector<std::function<void()>> _checkers;
    std::vector<std::function<void()>> _post_eval_services;
    std::vector<std::function<void()>> _auto_cov_reports;
};

"#,
    );
}

/// M3: Deepened `HarcTestContext` — runtime seam for separate compilation.
///
/// Extends the simple state-bag with owned submodules and lifecycle
/// methods so shared generated code operates on `HarcTestContext&` plus
/// its owning testbench instance, never on captured `run_<Test>` locals.
/// Header declares the struct and its methods; `context_methods` defines
/// them in the common source. Keeps the same layout as the simple
/// struct for the self-contained fallback, adding only member
/// declarations.
pub(super) fn context_struct_deepened(out: &mut String, dut_type: &str) {
    writeln!(out, "struct HarcTestContext {{").ok();
    writeln!(out, "{INDENT}V{dut_type}* dut = nullptr;").ok();
    out.push_str(
        r#"#if HARC_TRACE_ENABLED
    HarcTraceC* tfp = nullptr;
    std::string _wave_path;
#endif
    uint64_t _trace_time = 0;
    int errors = 0;
    bool _fatal = false;
    int cycle_count = 0;
    harc_rt::trace::HarcTraceWriter trace;
    harc_rt::log::HarcLogContext log_ctx;
    std::vector<std::function<void()>> _checkers;
    std::vector<std::function<void()>> _post_eval_services;
    std::vector<std::function<void()>> _auto_cov_reports;
    // M3: Per-test RNG and scheduler state — previously file-scope
    // `harc_rng` and per-`run_<Test>` locals. Now owned by the
    // context so two sequential runs in one process remain isolated
    // and shared code never captures a `run_<Test>` stack frame.
    harc_rt::random::HarcRng rng;
    harc_rt::ThreadScheduler scheduler;
    // Clock scheduler state — empty for single-clock tests, populated
    // for multi-clock tests. Kept on the context so `tick()` can be
    // a context method.
    struct ClockState { const char* name; long long half_period_ps; long long next_edge_ps; int level; long long rising_count; };
    std::vector<ClockState> _clocks;
    long long _now_ps = 0;

    // Lifecycle seam — shared code calls these, shards provide only
    // test-owned bodies.
    void start(const char* test_name, int argc, char** argv);
    void tick();
    void eval_clocks_until(long long t_ps);
    int finish();
    void _trace_dump_next(const char* clock, uint64_t cycle);
    void _trace_dump_at(uint64_t t, const char* clock, uint64_t cycle);
    void _log_wave_file();
};

"#,
    );
}

/// M3: Out-of-line definitions for the deepened `HarcTestContext` seam.
/// Emitted once into the common source, not into every shard.
pub(super) fn context_methods(out: &mut String, dut_type: &str) {
    writeln!(out, "void HarcTestContext::start(const char* test_name, int argc, char** argv) {{").ok();
    writeln!(out, "{INDENT}Verilated::commandArgs(argc, argv);").ok();
    writeln!(out, "{INDENT}dut = new V{dut_type};", dut_type = dut_type).ok();
    writeln!(out, "#if HARC_TRACE_ENABLED").ok();
    writeln!(out, "{INDENT}Verilated::traceEverOn(true);").ok();
    writeln!(out, "{INDENT}tfp = new HarcTraceC;").ok();
    writeln!(
        out,
        "{INDENT}_wave_path = harc_rt::log::harc_open_wave_trace(dut, tfp, harc_rt::log::harc_wave_default_name());"
    )
    .ok();
    writeln!(out, "#endif").ok();
    writeln!(out, "{INDENT}rng.seed_from_env();").ok();
    writeln!(
        out,
        "{INDENT}harc_rt::trace::harc_start_trace(trace, rng.state, \"{dut_type}\", test_name, cycle_count);",
        dut_type = dut_type
    )
    .ok();
    writeln!(out, "{INDENT}HARC_RT_LOG_WAVE_FILE(log_ctx.sim_log, _wave_path);").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(out, "void HarcTestContext::_trace_dump_next(const char* clock, uint64_t cycle) {{").ok();
    writeln!(out, "{INDENT}uint64_t t = _trace_time++;").ok();
    writeln!(out, "{INDENT}trace.set_timing(t, clock, cycle);").ok();
    writeln!(out, "{INDENT}HARC_RT_DUMP_WAVE_TRACE(tfp, t);").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(out, "void HarcTestContext::_trace_dump_at(uint64_t t, const char* clock, uint64_t cycle) {{").ok();
    writeln!(out, "{INDENT}trace.set_timing(t, clock, cycle);").ok();
    writeln!(out, "{INDENT}HARC_RT_DUMP_WAVE_TRACE(tfp, t);").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(out, "void HarcTestContext::_log_wave_file() {{").ok();
    writeln!(out, "{INDENT}HARC_RT_LOG_WAVE_FILE(log_ctx.sim_log, _wave_path);").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(out, "void HarcTestContext::eval_clocks_until(long long t_ps) {{").ok();
    writeln!(out, "{INDENT}while (_now_ps < t_ps) {{").ok();
    writeln!(out, "{INDENT}{INDENT}long long next = t_ps;").ok();
    writeln!(out, "{INDENT}{INDENT}for (auto& c : _clocks) if (c.next_edge_ps < next) next = c.next_edge_ps;").ok();
    writeln!(out, "{INDENT}{INDENT}_now_ps = next;").ok();
    writeln!(out, "{INDENT}{INDENT}bool _primary_rising = false;").ok();
    writeln!(out, "{INDENT}{INDENT}const char* _last_edge_clock = \"\";").ok();
    writeln!(out, "{INDENT}{INDENT}uint64_t _last_edge_cycle = 0;").ok();
    writeln!(out, "{INDENT}{INDENT}for (size_t i = 0; i < _clocks.size(); i++) {{").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}auto& c = _clocks[i];").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}if (c.next_edge_ps == _now_ps) {{").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}{INDENT}c.level = !c.level;").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}{INDENT}if (dut) dut->eval(); // updated via clock writes").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}{INDENT}c.next_edge_ps += c.half_period_ps;").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}{INDENT}if (c.level == 1) c.rising_count++;").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}{INDENT}_last_edge_clock = c.name;").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}{INDENT}_last_edge_cycle = (uint64_t)c.rising_count;").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}{INDENT}if (i == 0 && c.level == 1) {{ cycle_count++; _primary_rising = true; }}").ok();
    writeln!(out, "{INDENT}{INDENT}{INDENT}}}").ok();
    writeln!(out, "{INDENT}{INDENT}}}").ok();
    writeln!(out, "{INDENT}{INDENT}if (dut) dut->eval();").ok();
    writeln!(out, "{INDENT}{INDENT}trace.set_timing((uint64_t)_now_ps, _last_edge_clock, _last_edge_cycle);").ok();
    writeln!(out, "{INDENT}{INDENT}if (_primary_rising) {{ for (auto& _svc : _post_eval_services) _svc(); if (!_post_eval_services.empty() && dut) dut->eval(); }}").ok();
    writeln!(out, "{INDENT}{INDENT}_trace_dump_at((uint64_t)_now_ps, _last_edge_clock, _last_edge_cycle);").ok();
    writeln!(out, "{INDENT}}}").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(out, "void HarcTestContext::tick() {{").ok();
    writeln!(out, "{INDENT}if (_clocks.empty()) {{").ok();
    writeln!(out, "{INDENT}{INDENT}_harc_eval_negedge(dut);").ok();
    writeln!(out, "{INDENT}{INDENT}_trace_dump_next(\"clk\", (uint64_t)cycle_count);").ok();
    writeln!(out, "{INDENT}{INDENT}_harc_eval_posedge(dut);").ok();
    writeln!(out, "{INDENT}{INDENT}_trace_dump_next(\"clk\", (uint64_t)(cycle_count + 1));").ok();
    writeln!(out, "{INDENT}{INDENT}cycle_count++;").ok();
    writeln!(out, "{INDENT}{INDENT}for (auto& _svc : _post_eval_services) _svc();").ok();
    writeln!(out, "{INDENT}{INDENT}if (!_post_eval_services.empty() && dut) dut->eval();").ok();
    writeln!(out, "{INDENT}{INDENT}if (!_post_eval_services.empty()) _trace_dump_next(\"clk\", (uint64_t)cycle_count);").ok();
    writeln!(out, "{INDENT}{INDENT}for (auto& _c : _checkers) _c();").ok();
    writeln!(out, "{INDENT}}} else {{").ok();
    writeln!(out, "{INDENT}{INDENT}long long target = _now_ps + _clocks[0].half_period_ps * 2;").ok();
    writeln!(out, "{INDENT}{INDENT}eval_clocks_until(target);").ok();
    writeln!(out, "{INDENT}{INDENT}for (auto& _c : _checkers) _c();").ok();
    writeln!(out, "{INDENT}}}").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(out, "int HarcTestContext::finish() {{").ok();
    writeln!(out, "{INDENT}for (auto& _r : _auto_cov_reports) _r();").ok();
    writeln!(out, "{INDENT}if (dut) dut->final();").ok();
    writeln!(out, "{INDENT}HARC_RT_WRITE_COVERAGE(Verilated::threadContextp()->coveragep());").ok();
    writeln!(out, "{INDENT}HARC_RT_CLOSE_WAVE_TRACE(tfp);").ok();
    writeln!(out, "{INDENT}if (dut) delete dut;").ok();
    writeln!(out, "{INDENT}return harc_rt::log::harc_finish_sim_run(log_ctx, trace, cycle_count, errors);").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();
}

/// `run_<Test>` prologue: context construction, alias refs, wave trace
/// setup, RNG seed, trace writer and dump lambdas.
pub(super) fn run_prologue(out: &mut String, test_name: &str, dut_type: &str, cosim: bool) {
    if cosim {
        // Co-sim form: runs on the bridge's TB thread (see
        // harc_cosim_rt.h). The simulator owns argv and time, so no
        // commandArgs; everything else matches the direct emission.
        writeln!(out, "int run_{test_name}() {{").ok();
    } else {
        writeln!(out, "int run_{test_name}(int argc, char** argv) {{").ok();
        writeln!(out, "{INDENT}Verilated::commandArgs(argc, argv);").ok();
    }
    writeln!(out, "{INDENT}HarcTestContext ctx;").ok();
    writeln!(out, "{INDENT}ctx.dut = new V{dut_type};").ok();
    out.push_str(
        r#"    auto* dut = ctx.dut;
#if HARC_TRACE_ENABLED
    auto* tfp = ctx.tfp;
    auto& _wave_path = ctx._wave_path;
#endif
    auto& _trace_time = ctx._trace_time;
    auto& errors = ctx.errors;
    auto& _fatal = ctx._fatal;
    auto& cycle_count = ctx.cycle_count;
    auto& trace = ctx.trace;
    auto& log_ctx = ctx.log_ctx;
    auto& _checkers = ctx._checkers;
    auto& _post_eval_services = ctx._post_eval_services;
    auto& _auto_cov_reports = ctx._auto_cov_reports;
#if HARC_TRACE_ENABLED
    Verilated::traceEverOn(true);
    tfp = new HarcTraceC;
    _wave_path = harc_rt::log::harc_open_wave_trace(dut, tfp, harc_rt::log::harc_wave_default_name());
#endif

    harc_rng.seed_from_env();
"#,
    );
    writeln!(
        out,
        "{INDENT}harc_rt::trace::harc_start_trace(trace, harc_rng.state, \"{dut_type}\", \"{test_name}\", cycle_count);"
    )
    .ok();
    out.push_str(
        r#"    auto _harc_trace_dump_next = [&](const char* clock, uint64_t clock_cycle) {
        uint64_t t = _trace_time++;
        trace.set_timing(t, clock, clock_cycle);
        HARC_RT_DUMP_WAVE_TRACE(tfp, t);
    };
    auto _harc_trace_dump_at = [&](uint64_t t, const char* clock, uint64_t clock_cycle) {
        trace.set_timing(t, clock, clock_cycle);
        HARC_RT_DUMP_WAVE_TRACE(tfp, t);
    };

    HARC_RT_LOG_WAVE_FILE(log_ctx.sim_log, _wave_path);


"#,
    );
}

/// Multi-clock scheduler (declared `clock` ports): `clocks_` vector +
/// `eval_clocks_until` + `tick`. Mirrors v1's emission exactly.
pub(super) fn clocked_scheduler(out: &mut String, clocks: &[ClockSpec]) {
    writeln!(out, "{INDENT}long long now_ps = 0;").ok();
    writeln!(out, "{INDENT}struct ClockState {{ const char* name; long long half_period_ps; long long next_edge_ps; int level; long long rising_count; }};").ok();
    writeln!(out, "{INDENT}std::vector<ClockState> clocks_;").ok();
    for c in clocks {
        let half = c.period_ps / 2;
        writeln!(
            out,
            "{INDENT}clocks_.push_back(ClockState{{\"{}\", {half}, {half}, 0, 0}});",
            c.name
        )
        .ok();
        writeln!(out, "{INDENT}dut->{} = 0;", c.name).ok();
    }
    writeln!(out).ok();
    out.push_str(
        r#"    auto eval_clocks_until = [&](long long t_ps) {
        while (now_ps < t_ps) {
            long long next = t_ps;
            for (auto& c : clocks_) if (c.next_edge_ps < next) next = c.next_edge_ps;
            now_ps = next;
            bool _primary_rising = false;
            const char* _last_edge_clock = "";
            uint64_t _last_edge_cycle = 0;
            for (size_t i = 0; i < clocks_.size(); i++) {
                auto& c = clocks_[i];
                if (c.next_edge_ps == now_ps) {
                    c.level = !c.level;
"#,
    );
    for (idx, c) in clocks.iter().enumerate() {
        writeln!(
            out,
            "{INDENT}{INDENT}{INDENT}{INDENT}{INDENT}if (i == {idx}) dut->{} = c.level;",
            c.name
        )
        .ok();
    }
    out.push_str(
        r#"                    c.next_edge_ps += c.half_period_ps;
                    if (c.level == 1) c.rising_count++;
                    _last_edge_clock = c.name;
                    _last_edge_cycle = (uint64_t)c.rising_count;
                    if (i == 0 && c.level == 1) { cycle_count++; _primary_rising = true; }
                }
            }
            dut->eval();
            // Set the semantic trace timing for this edge *before* running
            // post_eval services so any trace events they emit carry the
            // correct time, but defer the waveform dump until after those
            // services (and the follow-up eval) have settled DUT-visible
            // state. VCD cannot represent two dumps at the same physical
            // timestamp, so we dump exactly once per `now_ps` (issue #477).
            trace.set_timing((uint64_t)now_ps, _last_edge_clock, _last_edge_cycle);
            if (_primary_rising) { for (auto& _svc : _post_eval_services) _svc(); if (!_post_eval_services.empty()) dut->eval(); }
            _harc_trace_dump_at((uint64_t)now_ps, _last_edge_clock, _last_edge_cycle);
        }
    };

    auto tick = [&]() {
        long long target = now_ps + clocks_[0].half_period_ps * 2;
        eval_clocks_until(target);
        for (auto& _c : _checkers) _c();
    };

"#,
    );
}

/// Single-clock backward-compat `tick` (no declared clocks).
///
/// Clockless tests historically only had synthetic cycle time via
/// `tick()`. TB-IR also lowers wall-clock waits to
/// `eval_clocks_until(now_ps + N)`, so provide a minimal absolute-time
/// runtime here: wall waits settle the DUT at the requested picosecond
/// timestamp, while normal cycle ticks keep `now_ps` synchronized to the
/// trace timeline.
pub(super) fn clockless_scheduler(out: &mut String) {
    out.push_str(
        r#"    long long now_ps = 0;
    auto eval_clocks_until = [&](long long t_ps) {
        if (t_ps <= now_ps) return;
        now_ps = t_ps;
        dut->eval();
        _harc_trace_dump_at((uint64_t)now_ps, "", (uint64_t)cycle_count);
        if (_trace_time <= (uint64_t)now_ps) _trace_time = (uint64_t)now_ps + 1;
    };

    auto tick = [&]() {
        _harc_eval_negedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)cycle_count);
        now_ps = (long long)_trace_time;
        _harc_eval_posedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)(cycle_count + 1));
        now_ps = (long long)_trace_time;
        cycle_count++;
        for (auto& _svc : _post_eval_services) _svc();
        if (!_post_eval_services.empty()) dut->eval();
        if (!_post_eval_services.empty()) { _harc_trace_dump_next("clk", (uint64_t)cycle_count); now_ps = (long long)_trace_time; }
        for (auto& _c : _checkers) _c();
    };

"#,
    );
}

/// Log lambdas + seed line + scheduler declaration.
pub(super) fn log_helpers_and_seed(out: &mut String) {
    out.push_str(
        r#"    auto sim_logf_line = [&](FILE* f, const char* sev, const char* fmt, ...) {
        HARC_RT_LOG_FILE_ONLY_PRINTF(f, cycle_count, sev, fmt);
    };

    auto sim_log_line = [&](const char* sev, const char* fmt, ...) {
        HARC_RT_LOG_PRINTF(log_ctx.sim_log, &trace, cycle_count, sev, fmt);
    };

    // Route an empty-queue pop through the sim's own FATAL path instead
    // of the runtime header's abort backstop: the run records the
    // failure, unwinds normally, and still writes its log and trace.
    // `_fatal` is a loop-exit condition, so the run stops at the next
    // scheduler tick — same semantics as `log(fatal, ...)`. Emitted
    // verbatim by both codegens so the two traces stay diffable.
    harc_rt::HarcQueueFatalScope _queue_fatal_scope([&]() {
        sim_log_line("FATAL", "pop() on an empty queue -- guard it with .empty()/.size(), or wait until the producer has pushed");
        ctx.errors++;
        _fatal = true;
    });

    sim_log_line("INFO", "seed=%llu", (long long)harc_rng.state);

    harc_rt::ThreadScheduler sched;
"#,
    );
}

/// Register an actor coroutine slot. Cooperative (`mt=false`) mode pushes
/// the slot into the global `sched` (single-threaded round-robin). Under
/// `--mt`, the actor gets a dedicated `harc_rt::ThreadScheduler` (declared
/// here) running on its own OS worker thread; the `(sched, slot)` pair is
/// recorded in `actor_threads` so the worker-spawn / barrier dance picks
/// it up. Mirrors v1's per-slot scheduler split (`cpp_tb.rs:6178`,
/// `6598`, multi-lane variants) verbatim — every actor slot becomes its
/// own worker thread.
pub(super) fn register_actor_slot(
    out: &mut String,
    mt: bool,
    actor_threads: &mut Vec<(String, String)>,
    sched_var: &str,
    slot_var: &str,
    depth: usize,
) {
    let pad = INDENT.repeat(depth);
    if mt {
        writeln!(out, "{pad}harc_rt::ThreadScheduler {sched_var};").ok();
        writeln!(out, "{pad}harc_rt::ThreadSlot {slot_var};").ok();
        writeln!(out, "{pad}{sched_var}.slots.push_back(&{slot_var});").ok();
        actor_threads.push((sched_var.to_string(), slot_var.to_string()));
    } else {
        writeln!(out, "{pad}harc_rt::ThreadSlot {slot_var};").ok();
        writeln!(out, "{pad}sched.slots.push_back(&{slot_var});").ok();
    }
}

/// `--mt` worker-thread topology, emitted after the run-slot is set up and
/// before the drive loop. Ports v1's `cpp_tb.rs:2440-2492` verbatim: a
/// shutdown flag, two `N+1`-participant barriers (main + N workers), and
/// one `std::thread` per actor running the dual-barrier loop
/// `while(true){ start.wait(); if(shutdown) break; sched.tick(); end.wait(); }`.
/// Each per-actor scheduler must already be `bootstrap()`-ed (single
/// threaded) before the workers spin up. No-op when `actor_threads` is
/// empty (cooperative mode / no actors).
pub(super) fn mt_worker_setup(out: &mut String, actor_threads: &[(String, String)]) {
    if actor_threads.is_empty() {
        return;
    }
    let n = actor_threads.len();
    writeln!(
        out,
        "{INDENT}// Phase 3a: per-actor OS threads with dual barrier sync."
    )
    .ok();
    writeln!(
        out,
        "{INDENT}// {n} actor(s) → {} barrier participants (main + workers).",
        n + 1
    )
    .ok();
    writeln!(out, "{INDENT}std::atomic<bool> _shutdown{{false}};").ok();
    writeln!(out, "{INDENT}harc_rt::Barrier _start_barrier({});", n + 1).ok();
    writeln!(out, "{INDENT}harc_rt::Barrier _end_barrier({});", n + 1).ok();
    writeln!(out, "{INDENT}std::vector<std::thread> _workers;").ok();
    for (sched_var, _) in actor_threads {
        writeln!(out, "{INDENT}_workers.emplace_back([&]() {{").ok();
        writeln!(out, "{INDENT}{INDENT}while (true) {{").ok();
        writeln!(out, "{INDENT}{INDENT}{INDENT}_start_barrier.wait();").ok();
        writeln!(
            out,
            "{INDENT}{INDENT}{INDENT}if (_shutdown.load(std::memory_order_acquire)) break;"
        )
        .ok();
        writeln!(out, "{INDENT}{INDENT}{INDENT}{sched_var}.tick();").ok();
        writeln!(out, "{INDENT}{INDENT}{INDENT}_end_barrier.wait();").ok();
        writeln!(out, "{INDENT}{INDENT}}}").ok();
        writeln!(out, "{INDENT}}});").ok();
    }
    writeln!(out).ok();
}

/// `--mt` shutdown sequence, emitted after the drive loop. Ports v1's
/// `cpp_tb.rs:2672-2685`: workers are parked on `_start_barrier` awaiting
/// their next iteration; set `_shutdown`, wake them through the start
/// barrier so they observe the flag and break before reaching
/// `_end_barrier`, then join. No-op in cooperative mode.
pub(super) fn mt_worker_shutdown(out: &mut String, actor_threads: &[(String, String)]) {
    if actor_threads.is_empty() {
        return;
    }
    writeln!(out).ok();
    writeln!(
        out,
        "{INDENT}_shutdown.store(true, std::memory_order_release);"
    )
    .ok();
    writeln!(out, "{INDENT}_start_barrier.wait();").ok();
    writeln!(out, "{INDENT}for (auto& _w : _workers) _w.join();").ok();
}

/// Bootstrap fan-out: resume the global scheduler, then each per-actor
/// scheduler (`--mt`), all single-threaded — emitted BEFORE the worker
/// threads spin up (`mt_worker_setup`) so every actor's initial-setup
/// statements run race-free. Mirrors v1's `cpp_tb.rs:2417-2438`.
pub(super) fn drive_bootstrap(out: &mut String, actor_threads: &[(String, String)]) {
    out.push_str(
        r#"
    // Resume each coroutine once so initial-setup statements run
    // before the first clock edge. Single-threaded — workers
    // haven't been spawned yet.
    sched.bootstrap();
"#,
    );
    for (sched_var, _) in actor_threads {
        writeln!(out, "{INDENT}{sched_var}.bootstrap();").ok();
    }
}

/// Main drive loop. `clocked` selects between the eval_clocks_until loop
/// and the negedge/posedge loop, mirroring v1. When `actor_threads` is
/// non-empty (`--mt`), the loop fences the worker tick between
/// `_start_barrier.wait()` / `_end_barrier.wait()` after `sched.tick()`
/// and before the `_checkers` fan-out — so the run-coroutine's writes
/// complete before workers wake, and the workers' DUT-input writes
/// complete before the next eval (no shared-state race). Mirrors v1's
/// barrier gating (`cpp_tb.rs:2621-2667`) verbatim. Bootstrap is emitted
/// separately by `drive_bootstrap` (the worker spawn sits between).
pub(super) fn drive_loop(out: &mut String, clocked: bool, actor_threads: &[(String, String)]) {
    let mt = !actor_threads.is_empty();
    out.push_str(
        r#"
    // Drive the clock until the run coroutine completes.
    //
    // `wait N cycles` matches Verilog's `@(posedge clk)` semantic:
    // values set in the segment BEFORE the wait are sampled at the
    // next posedge. Per loop iteration:
    //   1. Posedge (clk 0→1, eval) — DUT FFs latch the current input
    //      values (set in the previous segment, or in bootstrap on
    //      the first iteration).
    //   2. `sched.tick()` — advance the run coroutine to its next
    //      wait, setting the inputs for the NEXT cycle's posedge.
    //   3. Falling edge (clk 1→0, eval) — comb re-settles with the
    //      newly-set inputs.
    //   4. Cycle counter + checkers.
    // One initial `eval(clk=0)` before the loop settles combinational
    // logic with the bootstrap inputs — same role as `initial`-block
    // settle in Verilog. Each `wait 1 cycle` then maps to exactly
    // one posedge that observes the just-set values.
"#,
    );
    if mt {
        out.push_str(
            r#"    //
    // MT mode: workers run between tick() and the falling edge, gated by
    // _start_barrier / _end_barrier. Run-coroutine writes complete BEFORE
    // workers wake → no race on shared queues. Workers' DUT-input writes
    // complete BEFORE the falling-edge eval → no race on signal state.
"#,
        );
    }

    let barrier_gate = if mt {
        "        _start_barrier.wait();\n        _end_barrier.wait();\n"
    } else {
        ""
    };
    if clocked {
        out.push_str(
            r#"    dut->eval();
    _harc_trace_dump_at((uint64_t)now_ps, "", 0);
    while (_run_slot.kind != harc_rt::WaitKind::Done && !_fatal) {
        long long _target = now_ps + clocks_[0].half_period_ps * 2;
        eval_clocks_until(_target);
        sched.tick();
"#,
        );
        out.push_str(barrier_gate);
        out.push_str(
            r#"        for (auto& _c : _checkers) _c();
    }
"#,
        );
    } else {
        out.push_str(
            r#"    _harc_eval_negedge(dut);
    _harc_trace_dump_next("clk", (uint64_t)cycle_count);
    now_ps = (long long)_trace_time;
    while (_run_slot.kind != harc_rt::WaitKind::Done && !_fatal) {
        _harc_eval_posedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)(cycle_count + 1));
        now_ps = (long long)_trace_time;
        cycle_count++;
        for (auto& _svc : _post_eval_services) _svc();
        if (!_post_eval_services.empty()) dut->eval();
        if (!_post_eval_services.empty()) { _harc_trace_dump_next("clk", (uint64_t)cycle_count); now_ps = (long long)_trace_time; }
        sched.tick();
"#,
        );
        out.push_str(barrier_gate);
        out.push_str(
            r#"        _harc_eval_negedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)cycle_count);
        now_ps = (long long)_trace_time;
        for (auto& _c : _checkers) _c();
    }
"#,
        );
    }
}

/// Coverage reports, finalization, exit status.
///
/// `covers` is the test's concurrent-`cover` checks in registration
/// order; each contributes a hit/total tally and a per-point report line
/// (v1's property-cover summary, ARCH-style: header then per-point lines
/// with a `*NOT HIT*` marker supplied by the runtime printer).
pub(super) fn run_epilogue(out: &mut String, cosim: bool, covers: &[&crate::ir::CoverCheckSchema]) {
    out.push_str(
        r#"

    for (auto& _r : _auto_cov_reports) _r();
"#,
    );
    if !covers.is_empty() {
        writeln!(out, "{INDENT}{{").ok();
        writeln!(
            out,
            "{INDENT}{INDENT}uint64_t _cov_total = {};",
            covers.len()
        )
        .ok();
        writeln!(out, "{INDENT}{INDENT}uint64_t _cov_hit = 0;").ok();
        for c in covers {
            let counter = super::func::cover_counter_name(&c.tag);
            writeln!(out, "{INDENT}{INDENT}if ({counter} > 0) _cov_hit++;").ok();
        }
        writeln!(
            out,
            "{INDENT}{INDENT}harc_rt::log::harc_print_cover_summary(_cov_hit, _cov_total);"
        )
        .ok();
        for c in covers {
            let counter = super::func::cover_counter_name(&c.tag);
            writeln!(
                out,
                "{INDENT}{INDENT}harc_rt::log::harc_print_cover_point(\"{}\", {counter});",
                super::expr::escape_c(&c.label)
            )
            .ok();
        }
        writeln!(out, "{INDENT}}}").ok();
    }
    out.push_str(
        r#"    dut->final();
"#,
    );
    if !cosim {
        // Verilator coverage belongs to the simulator process on the
        // co-sim path; the shim has no Verilated context to query.
        out.push_str("    HARC_RT_WRITE_COVERAGE(Verilated::threadContextp()->coveragep());\n");
    }
    out.push_str(
        r#"    HARC_RT_CLOSE_WAVE_TRACE(tfp);
    delete dut;

"#,
    );
    out.push_str(
        "    return harc_rt::log::harc_finish_sim_run(log_ctx, trace, cycle_count, errors);\n}\n\n",
    );
}

/// `main` dispatcher: `--test <name>` / `HARC_TEST` selection.
pub(super) fn dispatcher(out: &mut String, test_names: &[String]) {
    writeln!(out, "int main(int argc, char** argv) {{").ok();
    writeln!(
        out,
        "{INDENT}const char* test_sel = harc_rt::log::harc_select_test(argc, argv);"
    )
    .ok();
    let first = &test_names[0];
    writeln!(
        out,
        "{INDENT}if (!test_sel) return run_{first}(argc, argv);"
    )
    .ok();
    for name in test_names {
        writeln!(
            out,
            "{INDENT}if (std::strcmp(test_sel, \"{name}\") == 0) return run_{name}(argc, argv);"
        )
        .ok();
    }
    let avail = test_names.join(", ");
    writeln!(
        out,
        "{INDENT}harc_rt::log::harc_report_unknown_test(test_sel, \"{avail}\");"
    )
    .ok();
    writeln!(out, "{INDENT}return 1;").ok();
    writeln!(out, "}}").ok();
}

/// Co-sim entrypoints (`--cosim dpi`): replaces `main()`. The generated
/// `HarcCosimTop.sv` harness imports these over DPI-C; test selection
/// comes from `HARC_TEST` (the harc CLI sets it — Verilator's generated
/// `main()` owns argv on this path). The selected `run_<Test>` executes
/// on the bridge's dedicated TB thread under a strict handshake: the
/// simulator thread stays parked inside `harc_cosim_step` while the TB
/// runs, so all TB-side simulator access happens inside a DPI
/// entrypoint by delegation (see harc_cosim_rt.h). `run_until_request`
/// is idempotent after completion — Verilator defers $finish to the end
/// of the timestep, so the master process may step once more after the
/// test finishes.
pub(super) fn cosim_entrypoints(out: &mut String, test_names: &[String], half_period_ps: u64) {
    out.push_str(
        r#"extern "C" void harc_cosim_init() {
    auto& _b = harc_rt::cosim::bridge();
"#,
    );
    writeln!(out, "{INDENT}_b.half_period_ps = {half_period_ps};").ok();
    out.push_str(
        r#"    _b.vl_ctx = Verilated::threadContextp();
    _b.vl_scope = svGetScope();
    const char* test_sel = harc_rt::log::harc_select_test(0, nullptr);
"#,
    );
    let first = &test_names[0];
    writeln!(
        out,
        "{INDENT}if (!test_sel) {{ _b.body = &run_{first}; return; }}"
    )
    .ok();
    for name in test_names {
        writeln!(
            out,
            "{INDENT}if (std::strcmp(test_sel, \"{name}\") == 0) {{ _b.body = &run_{name}; return; }}"
        )
        .ok();
    }
    let avail = test_names.join(", ");
    writeln!(
        out,
        "{INDENT}harc_rt::log::harc_report_unknown_test(test_sel, \"{avail}\");"
    )
    .ok();
    writeln!(out, "{INDENT}_b.body = nullptr;").ok();
    writeln!(out, "}}").ok();
    out.push_str(
        r#"
extern "C" long long harc_cosim_step() {
    auto& _b = harc_rt::cosim::bridge();
    if (!_b.body) return harc_rt::cosim::RC_DONE_FAIL;
    return _b.run_until_request();
}

// Called from the harness's `final` block on every simulation end.
// Detects ends the HARC runtime did not drive — most commonly a
// DUT-initiated $finish — which would otherwise exit 0 with no test
// summary while the TB thread is still parked on the bridge.
extern "C" void harc_cosim_shutdown() {
    auto& _b = harc_rt::cosim::bridge();
    if (_b.done || !_b.started) return;
    std::fflush(stdout);
    std::fprintf(stderr,
                 "FATAL: simulation ended outside HARC control (DUT-initiated "
                 "$finish/$stop?) before the test completed\n");
    std::fflush(stderr);
    // The TB thread is parked on the bridge and can never finish;
    // exit hard with a distinct status so callers see a failure, not
    // a silent zero-exit with no summary.
    std::_Exit(97);
}
"#,
    );
}
