//! Fixed C++ scaffolding for the TB-IR backend. Every block of text
//! here mirrors the live v1 (`cpp_tb`) emission contract byte-for-byte
//! where the output is runtime-observable (trace events, log lines,
//! clock scheduling), so the v1-vs-tbir equivalence gate can diff
//! normalized semantic traces.

use crate::ir::ClockSpec;
use std::fmt::Write as _;

pub(super) const INDENT: &str = "    ";

/// File preamble: includes, trace gates, eval helpers, RNG.
///
/// `problem_table_cpp` is the rendered constraint-solver runtime problem
/// table (`RuntimeProblemTable::render_cpp_table`) when the program has
/// any randomize site, else empty — its non-emptiness also gates the
/// `harc_z3_rt.h` include, mirroring v1's `uses_constraint_solver` gate.
pub(super) fn preamble(
    out: &mut String,
    dut_type: &str,
    test_names: &[String],
    problem_table_cpp: &str,
) {
    writeln!(out, "// Auto-generated by harc — do not edit.").ok();
    writeln!(out, "// Codegen: tbir (TB-IR loop-switch backend).").ok();
    writeln!(out, "// HARC test: {}", test_names.join(", ")).ok();
    out.push_str(
        "\n#ifdef __clang__\n#pragma clang optimize off\n#endif\n\n");
    writeln!(out, "#include \"V{dut_type}.h\"").ok();
    out.push_str(
        r#"#include "verilated.h"
#if VM_COVERAGE
#include "verilated_cov.h"
#endif
#if defined(HARC_TRACE_VCD)
#include "verilated_vcd_c.h"
#define HARC_TRACE_ENABLED 1
using HarcTraceC = VerilatedVcdC;
#elif defined(HARC_TRACE_FST)
#include "verilated_fst_c.h"
#define HARC_TRACE_ENABLED 1
using HarcTraceC = VerilatedFstC;
#else
#define HARC_TRACE_ENABLED 0
#endif
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstdarg>
#include <cstring>
#include <string>
#include <array>
#include <vector>
#include <deque>
#include <functional>
#include <thread>
#include <atomic>
#include "harc_thread_rt.h"
#include "harc_random_rt.h"
#include "harc_queue_rt.h"
#include "harc_trace_rt.h"
#include "harc_log_rt.h"
"#,
    );
    // Constraint-solver runtime: the Z3 helper header + the per-program
    // problem table, emitted only when a randomize site exists (v1's
    // `uses_constraint_solver` gate). Without a site, the generated TB
    // never links Z3 — same as v1.
    if !problem_table_cpp.is_empty() {
        writeln!(
            out,
            "#include \"harc_z3_rt.h\"   // randomize(t) with <constraints>"
        )
        .ok();
    }
    out.push_str(
        r#"
template<typename DUT>
static void _harc_eval_negedge(DUT* dut) {
    if constexpr (requires { dut->clk; }) { dut->clk = 0; }
    dut->eval();
}
template<typename DUT>
static void _harc_eval_posedge(DUT* dut) {
    if constexpr (requires { dut->clk; }) { dut->clk = 1; }
    dut->eval();
}

"#,
    );
    out.push_str(problem_table_cpp);
    out.push_str(
        r#"static harc_rt::random::HarcRng harc_rng;
static inline uint64_t harc_rng_next() {
    return harc_rng.next();
}

"#,
    );
}

/// One testbench struct (only for non-synthetic testbenches).
/// `cov_fields` are (field name, covergroup struct name) pairs in
/// declaration order, emitted after the DUT pointer — same member
/// layout as v1. `scalar_fields` are run/check-shared scalar members
/// (`expected : uint<32> default 0`), with v1's C-type mapping.
/// One scoreboard declaration → C++ struct (v1's `emit_scoreboard`
/// shape): scalar counters with their declared defaults, `queue<T>`
/// fields as `harc_rt::HarcQueue<T>` members. The activity-tracking
/// `_last_in/out_cycle` heartbeat fields v1 injects are NOT emitted —
/// the data-only subset never reads them (`sb.idle(N)` is an event-
/// driven predicate, out of this slice's scope).
/// One bound-to target-TLM responder instance: a test-scope local
/// struct (state fields + activity stamps) plus its instance, mirroring
/// v1's per-instance component struct. Declared inside the test function
/// so the run/check coroutine and the actor coroutines share it by `[&]`
/// reference. Emitted at one indent level (inside the test fn body).
pub(super) fn target_state_struct_inst(
    out: &mut String,
    schema: &crate::ir::TransactorSchema,
    instance: &str,
) {
    let ty = format!("_{}_{}_state", schema.name, instance);
    writeln!(out, "{INDENT}struct {ty} {{").ok();
    for f in &schema.state_fields {
        let (cty, init) = match f.ty {
            crate::ir::IrType::Bool => (
                "bool",
                if f.default != 0 { "true" } else { "false" }.to_string(),
            ),
            crate::ir::IrType::SInt(_) => ("int64_t", f.default.to_string()),
            _ => ("uint64_t", f.default.to_string()),
        };
        writeln!(out, "{INDENT}{INDENT}{cty} {} = {init};", f.name).ok();
    }
    // Activity stamps, mirroring v1's auto-injected component fields
    // (`idle()`/`idle_in()`/`idle_out()` predicate backing).
    writeln!(out, "{INDENT}{INDENT}uint64_t _last_in_cycle = 0;").ok();
    writeln!(out, "{INDENT}{INDENT}uint64_t _last_out_cycle = 0;").ok();
    writeln!(out, "{INDENT}}} {instance};").ok();
}

pub(super) fn scoreboard_struct(out: &mut String, sb: &crate::ir::ScoreboardSchema) {
    writeln!(out, "struct {} {{", sb.name).ok();
    for f in &sb.fields {
        match &f.kind {
            crate::ir::ScoreboardFieldKind::Scalar { ty, default } => {
                let (cty, init) = match ty {
                    crate::ir::IrType::Bool => (
                        "bool",
                        if *default != 0 { "true" } else { "false" }.to_string(),
                    ),
                    crate::ir::IrType::SInt(_) => ("int64_t", default.to_string()),
                    _ => ("uint64_t", default.to_string()),
                };
                writeln!(out, "{INDENT}{cty} {} = {init};", f.name).ok();
            }
            crate::ir::ScoreboardFieldKind::Queue { signed } => {
                let elem = if *signed { "int64_t" } else { "uint64_t" };
                writeln!(out, "{INDENT}harc_rt::HarcQueue<{elem}> {};", f.name).ok();
            }
        }
    }
    writeln!(out, "}};").ok();
    writeln!(out).ok();
}

/// The C++ payload type carried by an `event<T>` subscriber closure.
/// Mirrors v1's `payload_type_for_arg`: a scalar widens to
/// `uint64_t`/`int64_t`; a value-record payload is the record struct
/// (carried by value).
fn event_payload_cty(p: &crate::ir::EventPayload, records: &[crate::ir::RecordSchema]) -> String {
    match p {
        crate::ir::EventPayload::Scalar { signed: true } => "int64_t".to_string(),
        crate::ir::EventPayload::Scalar { signed: false } => "uint64_t".to_string(),
        crate::ir::EventPayload::Record(r) => records[r.index()].name.clone(),
    }
}

/// One composite-component struct (env/agent cluster, flat-struct
/// subset). Mirrors v1's `emit_component_struct`: scalar/queue/event/
/// sub-component fields plus the `_last_in_cycle`/`_last_out_cycle`
/// heartbeat stamps. Sub-component fields are emitted by their component
/// name, so file order (subs before the env that holds them) guarantees
/// the held type is already defined.
pub(super) fn component_struct(
    out: &mut String,
    c: &crate::ir::ComponentSchema,
    components: &[crate::ir::ComponentSchema],
    records: &[crate::ir::RecordSchema],
) {
    use crate::ir::ComponentFieldKind;
    writeln!(out, "struct {} {{", c.name).ok();
    for f in &c.fields {
        match &f.kind {
            ComponentFieldKind::Scalar { ty, default } => {
                let (cty, init) = match ty {
                    crate::ir::IrType::Bool => (
                        "bool",
                        if *default != 0 { "true" } else { "false" }.to_string(),
                    ),
                    crate::ir::IrType::SInt(_) => ("int64_t", default.to_string()),
                    _ => ("uint64_t", default.to_string()),
                };
                writeln!(out, "{INDENT}{cty} {} = {init};", f.name).ok();
            }
            ComponentFieldKind::Queue { signed } => {
                let elem = if *signed { "int64_t" } else { "uint64_t" };
                writeln!(out, "{INDENT}harc_rt::HarcQueue<{elem}> {};", f.name).ok();
            }
            ComponentFieldKind::Event { payload } => {
                let pty = event_payload_cty(payload, records);
                writeln!(
                    out,
                    "{INDENT}std::vector<std::function<void({pty})>> {};",
                    f.name
                )
                .ok();
            }
            ComponentFieldKind::Sub { component } => {
                let cname = &components[component.index()].name;
                writeln!(out, "{INDENT}{cname} {};", f.name).ok();
            }
        }
    }
    // v1's activity-tracking heartbeat stamps (read by idle predicates,
    // bumped on emit/in/out; carried for trace + future agent slice).
    writeln!(out, "{INDENT}uint64_t _last_in_cycle = 0;").ok();
    writeln!(out, "{INDENT}uint64_t _last_out_cycle = 0;").ok();
    writeln!(out, "}};").ok();
    writeln!(out).ok();
}

pub(super) fn tb_struct(
    out: &mut String,
    tb_name: &str,
    dut_type: &str,
    cov_fields: &[(String, String)],
    scalar_fields: &[crate::ir::TbScalarFieldSchema],
    scoreboard_fields: &[(String, String)],
) {
    writeln!(out, "struct {tb_name} {{").ok();
    writeln!(out, "{INDENT}V{dut_type}* dut = nullptr;").ok();
    for (field, cg_name) in cov_fields {
        writeln!(out, "{INDENT}{cg_name} {field};").ok();
    }
    for (field, sb_type) in scoreboard_fields {
        writeln!(out, "{INDENT}{sb_type} {field};").ok();
    }
    for f in scalar_fields {
        let (cty, init) = match f.ty {
            crate::ir::IrType::Bool => (
                "bool",
                if f.default != 0 { "true" } else { "false" }.to_string(),
            ),
            crate::ir::IrType::SInt(_) => ("int64_t", f.default.to_string()),
            _ => ("uint64_t", f.default.to_string()),
        };
        writeln!(out, "{INDENT}{cty} {} = {init};", f.name).ok();
    }
    writeln!(out, "{INDENT}uint64_t _last_in_cycle = 0;").ok();
    writeln!(out, "{INDENT}uint64_t _last_out_cycle = 0;").ok();
    writeln!(out, "}};").ok();
    writeln!(out).ok();
}

pub(super) fn context_struct(out: &mut String, dut_type: &str) {
    writeln!(out, "struct HarcTestContext {{").ok();
    writeln!(out, "{INDENT}V{dut_type}* dut = nullptr;").ok();
    out.push_str(
        r#"#if HARC_TRACE_ENABLED
    HarcTraceC* tfp = nullptr;
    std::string _wave_path;
#endif
    uint64_t _trace_time = 0;
    int errors = 0;
    bool _fatal = false;
    int cycle_count = 0;
    harc_rt::trace::HarcTraceWriter trace;
    harc_rt::log::HarcLogContext log_ctx;
    std::vector<std::function<void()>> _checkers;
    std::vector<std::function<void()>> _post_eval_services;
    std::vector<std::function<void()>> _auto_cov_reports;
};

"#,
    );
}

/// `run_<Test>` prologue: context construction, alias refs, wave trace
/// setup, RNG seed, trace writer and dump lambdas.
pub(super) fn run_prologue(out: &mut String, test_name: &str, dut_type: &str) {
    writeln!(out, "int run_{test_name}(int argc, char** argv) {{").ok();
    writeln!(out, "{INDENT}Verilated::commandArgs(argc, argv);").ok();
    writeln!(out, "{INDENT}HarcTestContext ctx;").ok();
    writeln!(out, "{INDENT}ctx.dut = new V{dut_type};").ok();
    out.push_str(
        r#"    auto*& dut = ctx.dut;
#if HARC_TRACE_ENABLED
    auto*& tfp = ctx.tfp;
    auto& _wave_path = ctx._wave_path;
#endif
    auto& _trace_time = ctx._trace_time;
    auto& errors = ctx.errors;
    auto& _fatal = ctx._fatal;
    auto& cycle_count = ctx.cycle_count;
    auto& trace = ctx.trace;
    auto& log_ctx = ctx.log_ctx;
    auto& _checkers = ctx._checkers;
    auto& _post_eval_services = ctx._post_eval_services;
    auto& _auto_cov_reports = ctx._auto_cov_reports;
#if HARC_TRACE_ENABLED
    Verilated::traceEverOn(true);
    tfp = new HarcTraceC;
    _wave_path = harc_rt::log::harc_open_wave_trace(dut, tfp, harc_rt::log::harc_wave_default_name());
#endif

    harc_rng.seed_from_env();
"#,
    );
    writeln!(
        out,
        "{INDENT}harc_rt::trace::harc_start_trace(trace, harc_rng.state, \"{dut_type}\", \"{test_name}\", cycle_count);"
    )
    .ok();
    out.push_str(
        r#"    auto _harc_trace_dump_next = [&](const char* clock, uint64_t clock_cycle) {
        uint64_t t = _trace_time++;
        trace.set_timing(t, clock, clock_cycle);
        HARC_RT_DUMP_WAVE_TRACE(tfp, t);
    };
    auto _harc_trace_dump_at = [&](uint64_t t, const char* clock, uint64_t clock_cycle) {
        trace.set_timing(t, clock, clock_cycle);
        HARC_RT_DUMP_WAVE_TRACE(tfp, t);
    };

    HARC_RT_LOG_WAVE_FILE(log_ctx.sim_log, _wave_path);


"#,
    );
}

/// Multi-clock scheduler (declared `clock` ports): `clocks_` vector +
/// `eval_clocks_until` + `tick`. Mirrors v1's emission exactly.
pub(super) fn clocked_scheduler(out: &mut String, clocks: &[ClockSpec]) {
    writeln!(out, "{INDENT}long long now_ps = 0;").ok();
    writeln!(out, "{INDENT}struct ClockState {{ const char* name; long long half_period_ps; long long next_edge_ps; int level; long long rising_count; }};").ok();
    writeln!(out, "{INDENT}std::vector<ClockState> clocks_;").ok();
    for c in clocks {
        let half = c.period_ps / 2;
        writeln!(
            out,
            "{INDENT}clocks_.push_back(ClockState{{\"{}\", {half}, {half}, 0, 0}});",
            c.name
        )
        .ok();
        writeln!(out, "{INDENT}dut->{} = 0;", c.name).ok();
    }
    writeln!(out).ok();
    out.push_str(
        r#"    auto eval_clocks_until = [&](long long t_ps) {
        while (now_ps < t_ps) {
            long long next = t_ps;
            for (auto& c : clocks_) if (c.next_edge_ps < next) next = c.next_edge_ps;
            now_ps = next;
            bool _primary_rising = false;
            const char* _last_edge_clock = "";
            uint64_t _last_edge_cycle = 0;
            for (size_t i = 0; i < clocks_.size(); i++) {
                auto& c = clocks_[i];
                if (c.next_edge_ps == now_ps) {
                    c.level = !c.level;
"#,
    );
    for (idx, c) in clocks.iter().enumerate() {
        writeln!(
            out,
            "{INDENT}{INDENT}{INDENT}{INDENT}{INDENT}if (i == {idx}) dut->{} = c.level;",
            c.name
        )
        .ok();
    }
    out.push_str(
        r#"                    c.next_edge_ps += c.half_period_ps;
                    if (c.level == 1) c.rising_count++;
                    _last_edge_clock = c.name;
                    _last_edge_cycle = (uint64_t)c.rising_count;
                    if (i == 0 && c.level == 1) { cycle_count++; _primary_rising = true; }
                }
            }
            dut->eval();
            _harc_trace_dump_at((uint64_t)now_ps, _last_edge_clock, _last_edge_cycle);
            if (_primary_rising) { for (auto& _svc : _post_eval_services) _svc(); if (!_post_eval_services.empty()) dut->eval(); }
            if (_primary_rising && !_post_eval_services.empty()) _harc_trace_dump_at((uint64_t)now_ps, _last_edge_clock, _last_edge_cycle);
        }
    };

    auto tick = [&]() {
        long long target = now_ps + clocks_[0].half_period_ps * 2;
        eval_clocks_until(target);
        for (auto& _c : _checkers) _c();
    };

"#,
    );
}

/// Single-clock backward-compat `tick` (no declared clocks).
pub(super) fn clockless_scheduler(out: &mut String) {
    out.push_str(
        r#"    auto tick = [&]() {
        _harc_eval_negedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)cycle_count);
        _harc_eval_posedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)(cycle_count + 1));
        cycle_count++;
        for (auto& _svc : _post_eval_services) _svc();
        if (!_post_eval_services.empty()) dut->eval();
        if (!_post_eval_services.empty()) _harc_trace_dump_next("clk", (uint64_t)cycle_count);
        for (auto& _c : _checkers) _c();
    };

"#,
    );
}

/// Log lambdas + seed line + scheduler declaration.
pub(super) fn log_helpers_and_seed(out: &mut String) {
    out.push_str(
        r#"    auto sim_logf_line = [&](FILE* f, const char* sev, const char* fmt, ...) {
        HARC_RT_LOG_FILE_ONLY_PRINTF(f, cycle_count, sev, fmt);
    };

    auto sim_log_line = [&](const char* sev, const char* fmt, ...) {
        HARC_RT_LOG_PRINTF(log_ctx.sim_log, &trace, cycle_count, sev, fmt);
    };

    sim_log_line("INFO", "seed=%llu", (long long)harc_rng.state);

    harc_rt::ThreadScheduler sched;
"#,
    );
}

/// Bootstrap + main drive loop. `clocked` selects between the
/// eval_clocks_until loop and the negedge/posedge loop, mirroring v1.
pub(super) fn drive_loop(out: &mut String, clocked: bool) {
    out.push_str(
        r#"
    // Resume each coroutine once so initial-setup statements run
    // before the first clock edge. Single-threaded — workers
    // haven't been spawned yet.
    sched.bootstrap();

    // Drive the clock until the run coroutine completes.
    //
    // `wait N cycles` matches Verilog's `@(posedge clk)` semantic:
    // values set in the segment BEFORE the wait are sampled at the
    // next posedge. Per loop iteration:
    //   1. Posedge (clk 0→1, eval) — DUT FFs latch the current input
    //      values (set in the previous segment, or in bootstrap on
    //      the first iteration).
    //   2. `sched.tick()` — advance the run coroutine to its next
    //      wait, setting the inputs for the NEXT cycle's posedge.
    //   3. Falling edge (clk 1→0, eval) — comb re-settles with the
    //      newly-set inputs.
    //   4. Cycle counter + checkers.
    // One initial `eval(clk=0)` before the loop settles combinational
    // logic with the bootstrap inputs — same role as `initial`-block
    // settle in Verilog. Each `wait 1 cycle` then maps to exactly
    // one posedge that observes the just-set values.
"#,
    );
    if clocked {
        out.push_str(
            r#"    dut->eval();
    _harc_trace_dump_at((uint64_t)now_ps, "", 0);
    while (_run_slot.kind != harc_rt::WaitKind::Done && !_fatal) {
        long long _target = now_ps + clocks_[0].half_period_ps * 2;
        eval_clocks_until(_target);
        sched.tick();
        for (auto& _c : _checkers) _c();
    }
"#,
        );
    } else {
        out.push_str(
            r#"    _harc_eval_negedge(dut);
    _harc_trace_dump_next("clk", (uint64_t)cycle_count);
    while (_run_slot.kind != harc_rt::WaitKind::Done && !_fatal) {
        _harc_eval_posedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)(cycle_count + 1));
        cycle_count++;
        for (auto& _svc : _post_eval_services) _svc();
        if (!_post_eval_services.empty()) dut->eval();
        if (!_post_eval_services.empty()) _harc_trace_dump_next("clk", (uint64_t)cycle_count);
        sched.tick();
        _harc_eval_negedge(dut);
        _harc_trace_dump_next("clk", (uint64_t)cycle_count);
        for (auto& _c : _checkers) _c();
    }
"#,
        );
    }
}

/// Coverage reports, finalization, exit status.
pub(super) fn run_epilogue(out: &mut String) {
    out.push_str(
        r#"

    for (auto& _r : _auto_cov_reports) _r();
    dut->final();
    HARC_RT_WRITE_COVERAGE(Verilated::threadContextp()->coveragep());
    HARC_RT_CLOSE_WAVE_TRACE(tfp);
    delete dut;

    return harc_rt::log::harc_finish_sim_run(log_ctx, trace, cycle_count, errors);
}

"#,
    );
}

/// `main` dispatcher: `--test <name>` / `HARC_TEST` selection.
pub(super) fn dispatcher(out: &mut String, test_names: &[String]) {
    writeln!(out, "int main(int argc, char** argv) {{").ok();
    writeln!(
        out,
        "{INDENT}const char* test_sel = harc_rt::log::harc_select_test(argc, argv);"
    )
    .ok();
    let first = &test_names[0];
    writeln!(out, "{INDENT}if (!test_sel) return run_{first}(argc, argv);").ok();
    for name in test_names {
        writeln!(
            out,
            "{INDENT}if (std::strcmp(test_sel, \"{name}\") == 0) return run_{name}(argc, argv);"
        )
        .ok();
    }
    let avail = test_names.join(", ");
    writeln!(
        out,
        "{INDENT}harc_rt::log::harc_report_unknown_test(test_sel, \"{avail}\");"
    )
    .ok();
    writeln!(out, "{INDENT}return 1;").ok();
    writeln!(out, "}}").ok();
}
