//! Z3 backend scaffold.
//!
//! This first slice renders a verified typed constraint problem into an
//! SMT-LIB/Z3-shaped text form. It does not invoke Z3 from Rust and does not
//! replace the existing `cpp_tb.rs` runtime solver path.

use std::collections::BTreeMap;

use crate::constraints::typed::*;
use crate::constraints::typed_verify::verify_constraint_problem;
use crate::solver::{FieldValue, SolvedTuple, SolverBackend, SolverBuildError, SolverResult};

#[derive(Debug, Default, Clone, Copy)]
pub struct Z3Backend;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Z3Problem {
    pub smt: String,
    pub assertions: Vec<Z3Assertion>,
    pub vars: BTreeMap<FieldPath, Z3Var>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Z3Assertion {
    pub name: String,
    pub origin: crate::constraints::ConstraintOrigin,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Z3Var {
    pub name: String,
    pub sort: Z3Sort,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Z3Sort {
    Bool,
    BitVec(u32),
}

impl Z3Sort {
    fn smt(&self) -> String {
        match self {
            Z3Sort::Bool => "Bool".to_string(),
            Z3Sort::BitVec(w) => format!("(_ BitVec {w})"),
        }
    }
}

impl SolverBackend for Z3Backend {
    type Problem = Z3Problem;
    type Model = ();

    fn build(&self, problem: &CTypedProblem) -> Result<Self::Problem, SolverBuildError> {
        verify_constraint_problem(problem).map_err(SolverBuildError::Verify)?;
        build_z3_problem(problem)
    }

    fn check(&self, _problem: &Self::Problem, _seed: u64) -> SolverResult<Self::Model> {
        SolverResult::Unknown("Rust Z3 execution is not wired yet".to_string())
    }

    fn extract(&self, _model: &Self::Model) -> SolvedTuple {
        SolvedTuple {
            fields: BTreeMap::<FieldPath, FieldValue>::new(),
        }
    }
}

fn build_z3_problem(problem: &CTypedProblem) -> Result<Z3Problem, SolverBuildError> {
    let mut vars = BTreeMap::new();
    let mut smt = String::new();
    smt.push_str("; generated by harc typed solver scaffold\n");
    smt.push_str("(set-logic QF_BV)\n");

    for (path, info) in &problem.env.fields {
        let Some(sort) = sort_for_type(&problem.env, &info.ty) else {
            return unsupported("field sort", format!("field `{path}` has type {}", info.ty));
        };
        let name = z3_field_name(path);
        smt.push_str(&format!("(declare-fun {name} () {})\n", sort.smt()));
        vars.insert(path.clone(), Z3Var { name, sort });
    }

    for (path, info) in &problem.env.fields {
        if let CType::Enum { domain } = info.ty {
            let Some(enum_info) = problem.env.enum_by_id(domain) else {
                return unsupported("enum domain", format!("missing enum domain #{}", domain.0));
            };
            let width = enum_width(enum_info.variants.len());
            smt.push_str(&format!(
                "(assert (bvult {} (_ bv{} {}))) ; enum {} domain\n",
                z3_field_name(path),
                enum_info.variants.len(),
                width,
                enum_info.name
            ));
        }
    }

    let mut assertions = Vec::new();
    for clause in &problem.constraints {
        let expr = lower_expr(problem, &clause.expr)?;
        let name = z3_assertion_name(&clause.assertion_name);
        smt.push_str(&format!("(assert (! {expr} :named {name}))\n"));
        assertions.push(Z3Assertion {
            name,
            origin: clause.origin.clone(),
        });
    }

    if let Some(order) = &problem.solve_order {
        let order = order
            .iter()
            .map(FieldPath::dotted)
            .collect::<Vec<_>>()
            .join(", ");
        smt.push_str(&format!("; solve_order({order})\n"));
    }

    smt.push_str("(check-sat)\n");
    Ok(Z3Problem {
        smt,
        assertions,
        vars,
    })
}

fn lower_expr(problem: &CTypedProblem, expr: &CTypedExpr) -> Result<String, SolverBuildError> {
    match &expr.kind {
        CExprKind::BvLit { value } => {
            let Some(width) = bv_width(&expr.ty) else {
                return unsupported("literal type", format!("BV literal has type {}", expr.ty));
            };
            Ok(format!("(_ bv{value} {width})"))
        }
        CExprKind::BoolLit(v) => Ok(v.to_string()),
        CExprKind::EnumLit {
            domain,
            variant_idx,
        } => {
            let Some(enum_info) = problem.env.enum_by_id(*domain) else {
                return unsupported("enum literal", format!("missing enum domain #{}", domain.0));
            };
            Ok(format!(
                "(_ bv{} {})",
                variant_idx,
                enum_width(enum_info.variants.len())
            ))
        }
        CExprKind::FieldRef(path) => Ok(z3_field_name(path)),
        CExprKind::LocalRef(local) => Ok(z3_local_name(*local)),
        CExprKind::Unary { op, expr: inner } => {
            let inner_s = lower_expr(problem, inner)?;
            let op_s = match op {
                CUnaryOp::Neg => "bvneg",
                CUnaryOp::LogicalNot => "not",
                CUnaryOp::BitNot => "bvnot",
            };
            Ok(format!("({op_s} {inner_s})"))
        }
        CExprKind::Binary { op, lhs, rhs } => {
            let lhs_s = lower_expr(problem, lhs)?;
            let rhs_s = lower_expr(problem, rhs)?;
            let op_s = binary_op_smt(*op, &lhs.ty)?;
            Ok(format!("({op_s} {lhs_s} {rhs_s})"))
        }
        CExprKind::InSet { expr, set } => {
            let expr_s = lower_expr(problem, expr)?;
            let CExprKind::Set(items) = &set.kind else {
                return unsupported("set membership", "rhs is not a set literal".to_string());
            };
            if items.is_empty() {
                return Ok("false".to_string());
            }
            let mut parts = Vec::new();
            for item in items {
                parts.push(format!("(= {expr_s} {})", lower_expr(problem, item)?));
            }
            Ok(join_bool("or", parts))
        }
        CExprKind::InRange { expr, lo, hi } => {
            let expr_s = lower_expr(problem, expr)?;
            let le = match bv_sign(&expr.ty) {
                Some(Sign::Signed) => "bvsle",
                Some(Sign::Unsigned) | None => "bvule",
            };
            let mut parts = Vec::new();
            if let Some(lo) = lo {
                parts.push(format!("({le} {} {expr_s})", lower_expr(problem, lo)?));
            }
            if let Some(hi) = hi {
                parts.push(format!("({le} {expr_s} {})", lower_expr(problem, hi)?));
            }
            Ok(join_bool("and", parts))
        }
        CExprKind::Set(_) | CExprKind::Range { .. } => unsupported(
            "standalone aggregate expression",
            format!("cannot lower `{expr}` as a standalone solver expression"),
        ),
        CExprKind::FieldMethodCall {
            target,
            method: BuiltinMethod::Len,
            args,
        } => {
            if !args.is_empty() {
                return unsupported("len()", "len() arguments are not supported".to_string());
            }
            let CExprKind::FieldRef(path) = &target.kind else {
                return unsupported(
                    "len() target",
                    "only field-rooted list len() is supported".to_string(),
                );
            };
            Ok(format!("{}__len", z3_field_name(path)))
        }
        CExprKind::ForAll { var, iter, body } => {
            let CType::List { elem, .. } = &iter.ty else {
                return unsupported("forall", format!("iterator has type {}", iter.ty));
            };
            let Some(sort) = sort_for_type(&problem.env, elem) else {
                return unsupported("forall", format!("local has type {}", elem));
            };
            let body_s = lower_expr(problem, body)?;
            Ok(format!(
                "(forall (({} {})) {body_s})",
                z3_local_name(*var),
                sort.smt()
            ))
        }
    }
}

fn binary_op_smt(op: CBinaryOp, lhs_ty: &CType) -> Result<&'static str, SolverBuildError> {
    let signed = matches!(bv_sign(lhs_ty), Some(Sign::Signed));
    Ok(match op {
        CBinaryOp::Add => "bvadd",
        CBinaryOp::Sub => "bvsub",
        CBinaryOp::Mul => "bvmul",
        CBinaryOp::Div if signed => "bvsdiv",
        CBinaryOp::Div => "bvudiv",
        CBinaryOp::Mod if signed => "bvsrem",
        CBinaryOp::Mod => "bvurem",
        CBinaryOp::Eq => "=",
        CBinaryOp::Ne => "distinct",
        CBinaryOp::Lt if signed => "bvslt",
        CBinaryOp::Lt => "bvult",
        CBinaryOp::Le if signed => "bvsle",
        CBinaryOp::Le => "bvule",
        CBinaryOp::Gt if signed => "bvsgt",
        CBinaryOp::Gt => "bvugt",
        CBinaryOp::Ge if signed => "bvsge",
        CBinaryOp::Ge => "bvuge",
        CBinaryOp::LogicalAnd => "and",
        CBinaryOp::LogicalOr => "or",
        CBinaryOp::BitAnd => "bvand",
        CBinaryOp::BitOr => "bvor",
        CBinaryOp::BitXor => "bvxor",
        CBinaryOp::Shl => "bvshl",
        CBinaryOp::Shr if signed => "bvashr",
        CBinaryOp::Shr => "bvlshr",
    })
}

fn sort_for_type(env: &FieldEnv, ty: &CType) -> Option<Z3Sort> {
    match ty {
        CType::Bool => Some(Z3Sort::Bool),
        CType::BV { width, .. } => Some(Z3Sort::BitVec(*width)),
        CType::Enum { domain } => env
            .enum_by_id(*domain)
            .map(|e| Z3Sort::BitVec(enum_width(e.variants.len()))),
        CType::Range { .. } | CType::Set { .. } | CType::List { .. } | CType::Bottom => None,
    }
}

fn bv_width(ty: &CType) -> Option<u32> {
    match ty {
        CType::BV { width, .. } => Some(*width),
        _ => None,
    }
}

fn bv_sign(ty: &CType) -> Option<Sign> {
    match ty {
        CType::BV { sign, .. } => Some(*sign),
        _ => None,
    }
}

fn enum_width(variant_count: usize) -> u32 {
    let values = variant_count.max(2) - 1;
    usize::BITS - values.leading_zeros()
}

fn z3_field_name(path: &FieldPath) -> String {
    format!("f_{}", sanitize(&path.dotted()))
}

fn z3_local_name(local: LocalId) -> String {
    format!("l_{}", local.0)
}

fn z3_assertion_name(name: &str) -> String {
    format!("a_{}", sanitize(name))
}

fn sanitize(s: &str) -> String {
    let mut out = String::new();
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(true)
    {
        out.insert(0, '_');
    }
    out
}

fn join_bool(op: &str, parts: Vec<String>) -> String {
    match parts.len() {
        0 => "true".to_string(),
        1 => parts.into_iter().next().unwrap(),
        _ => format!("({op} {})", parts.join(" ")),
    }
}

fn unsupported<T>(feature: &'static str, detail: String) -> Result<T, SolverBuildError> {
    Err(SolverBuildError::Unsupported { feature, detail })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constraints::typed::{
        CBinaryOp, CExprKind, CType, CTypedClause, CTypedExpr, CTypedProblem, ConstraintProblemId,
        EnumDomainEntry, FieldEnv, FieldInfo, FieldPath, ProblemOrigin,
    };
    use crate::constraints::{ConstraintOrigin, EnumVariantSchema};
    use crate::lexer::Span;

    fn base_problem(env: FieldEnv, expr: CTypedExpr) -> CTypedProblem {
        CTypedProblem {
            problem_id: ConstraintProblemId(7),
            origin: ProblemOrigin::BareRandomize {
                record: "Packet".to_string(),
                span: Span::default(),
            },
            env,
            constraints: vec![CTypedClause {
                origin: ConstraintOrigin::RandomizeWith {
                    span: Span::default(),
                },
                expr,
                assertion_name: "c.keep/0".to_string(),
            }],
            solve_order: None,
        }
    }

    fn field_info(ty: CType) -> FieldInfo {
        FieldInfo {
            ty,
            non_random: false,
            has_default: false,
            attrs: Vec::new(),
        }
    }

    #[test]
    fn builds_named_assertions_for_unsigned_constraints() {
        let mut env = FieldEnv::new();
        env.fields
            .insert(FieldPath::single("addr"), field_info(CType::uint(8)));
        let addr = CTypedExpr::new(
            CExprKind::FieldRef(FieldPath::single("addr")),
            CType::uint(8),
            Span::default(),
        );
        let four = CTypedExpr::new(
            CExprKind::BvLit { value: 4 },
            CType::uint(8),
            Span::default(),
        );
        let expr = CTypedExpr::new(
            CExprKind::Binary {
                op: CBinaryOp::Ge,
                lhs: Box::new(addr),
                rhs: Box::new(four),
            },
            CType::Bool,
            Span::default(),
        );
        let z3 = Z3Backend.build(&base_problem(env, expr)).expect("build");
        assert!(z3.smt.contains("(declare-fun f_addr () (_ BitVec 8))"));
        assert!(z3
            .smt
            .contains("(assert (! (bvuge f_addr (_ bv4 8)) :named a_c_keep_0))"));
        assert_eq!(z3.assertions[0].name, "a_c_keep_0");
    }

    #[test]
    fn signed_comparisons_use_signed_z3_ops() {
        let mut env = FieldEnv::new();
        env.fields
            .insert(FieldPath::single("delta"), field_info(CType::sint(8)));
        let delta = CTypedExpr::new(
            CExprKind::FieldRef(FieldPath::single("delta")),
            CType::sint(8),
            Span::default(),
        );
        let zero = CTypedExpr::new(
            CExprKind::BvLit { value: 0 },
            CType::sint(8),
            Span::default(),
        );
        let expr = CTypedExpr::new(
            CExprKind::Binary {
                op: CBinaryOp::Lt,
                lhs: Box::new(delta),
                rhs: Box::new(zero),
            },
            CType::Bool,
            Span::default(),
        );
        let z3 = Z3Backend.build(&base_problem(env, expr)).expect("build");
        assert!(z3.smt.contains("(bvslt f_delta (_ bv0 8))"));
    }

    #[test]
    fn enum_fields_get_bitvec_domain_axioms() {
        let mut env = FieldEnv::new();
        env.enums.push(EnumDomainEntry {
            id: EnumDomainId(0),
            name: "Op".to_string(),
            variants: vec![
                EnumVariantSchema {
                    enum_name: "Op".to_string(),
                    variant: "READ".to_string(),
                    index: 0,
                },
                EnumVariantSchema {
                    enum_name: "Op".to_string(),
                    variant: "WRITE".to_string(),
                    index: 1,
                },
                EnumVariantSchema {
                    enum_name: "Op".to_string(),
                    variant: "FLUSH".to_string(),
                    index: 2,
                },
            ],
        });
        let op_ty = CType::Enum {
            domain: EnumDomainId(0),
        };
        env.fields
            .insert(FieldPath::single("op"), field_info(op_ty.clone()));
        let op = CTypedExpr::new(
            CExprKind::FieldRef(FieldPath::single("op")),
            op_ty.clone(),
            Span::default(),
        );
        let write = CTypedExpr::new(
            CExprKind::EnumLit {
                domain: EnumDomainId(0),
                variant_idx: 1,
            },
            op_ty,
            Span::default(),
        );
        let expr = CTypedExpr::new(
            CExprKind::Binary {
                op: CBinaryOp::Eq,
                lhs: Box::new(op),
                rhs: Box::new(write),
            },
            CType::Bool,
            Span::default(),
        );
        let z3 = Z3Backend.build(&base_problem(env, expr)).expect("build");
        assert!(z3.smt.contains("(declare-fun f_op () (_ BitVec 2))"));
        assert!(z3
            .smt
            .contains("(assert (bvult f_op (_ bv3 2))) ; enum Op domain"));
        assert!(z3.smt.contains("(= f_op (_ bv1 2))"));
    }

    #[test]
    fn rejects_list_fields_until_aggregate_backend_lands() {
        let mut env = FieldEnv::new();
        env.fields.insert(
            FieldPath::single("items"),
            field_info(CType::List {
                elem: Box::new(CType::uint(8)),
                max_len: Some(4),
            }),
        );
        let expr = CTypedExpr::new(CExprKind::BoolLit(true), CType::Bool, Span::default());
        let err = Z3Backend
            .build(&base_problem(env, expr))
            .expect_err("list field declaration is unsupported in backend scaffold");
        assert!(matches!(
            err,
            SolverBuildError::Unsupported {
                feature: "field sort",
                ..
            }
        ));
    }

    #[test]
    fn malformed_ir_is_rejected_before_backend_lowering() {
        let env = FieldEnv::new();
        let expr = CTypedExpr::new(CExprKind::BoolLit(true), CType::Bottom, Span::default());
        let err = Z3Backend
            .build(&base_problem(env, expr))
            .expect_err("verifier should reject bottom type");
        assert!(matches!(err, SolverBuildError::Verify(_)));
    }
}
