//! Generates the SystemVerilog `bind` stub for HARC `probe` declarations.
//!
//! When a test's `let dut : T` carries a probe block, this emitter
//! produces `__harc_probe_<T>.sv` containing:
//!
//!   1. A module `__harc_probe_<T>` with one `logic` per declared probe,
//!      each annotated `/* verilator public_flat_rd */` so Verilator
//!      keeps it through optimization and exposes it as a top-level
//!      flat-readable member.
//!   2. `assign <probe> = <path>;` lines using upward references — the
//!      bound stub sits inside every instance of `T`, so unqualified
//!      paths like `alu0.a` resolve in that scope.
//!   3. A `bind T __harc_probe_<T> harc_probes ();` directive.
//!
//! Bind instance name is `harc_probes` (no leading underscore) so the
//! Verilator-mangled accessor is the clean form
//! `<T>__DOT__harc_probes__DOT__<probe_name>`, accessed via
//! `dut->rootp-><mangled>`. The header
//! `V<T>___024root.h` must be included in the emitted TB.

use crate::ast::*;
use std::fmt::Write;

/// Render a HARC `TypeExpr` as the SystemVerilog bit-width declarator
/// used inside the stub module — i.e. the part between `logic` and the
/// variable name. `bit` / `Bool` return an empty string for scalar.
fn sv_type_decl(ty: &TypeExpr) -> Result<String, String> {
    match ty {
        TypeExpr::Builtin { name, args, .. } => match name {
            BuiltinTy::Bit | BuiltinTy::Bool | BuiltinTy::BoolLower => Ok(String::new()),
            BuiltinTy::UInt | BuiltinTy::SInt | BuiltinTy::Bits
            | BuiltinTy::UIntCap | BuiltinTy::SIntCap => {
                let width = args.first().and_then(int_arg).ok_or_else(|| {
                    format!("probe type {name:?} needs a single integer width argument")
                })?;
                if width == 1 {
                    Ok(String::new())
                } else {
                    Ok(format!(" [{}:0]", width - 1))
                }
            }
            other => Err(format!("probe type {other:?} not supported (use uint<N>/sint<N>/bit)")),
        },
        TypeExpr::Named { name, .. } => {
            Err(format!("probe type `{}` not supported — use uint<N>, sint<N>, bits<N>, or bit",
                name.segments.last().map(|s| s.name.as_str()).unwrap_or("?")))
        }
    }
}

fn int_arg(a: &TypeArg) -> Option<u32> {
    match a {
        TypeArg::Expr(e) | TypeArg::Named { value: e, .. } => {
            if let ExprKind::Int(s) = &*e.kind {
                s.parse::<u32>().ok()
            } else {
                None
            }
        }
        TypeArg::Type(_) => None,
    }
}

/// Emit the full stub file contents.
///
/// Layout per probe:
/// - Read-only probe (`probe N : T at PATH`): one `logic` annotated
///   `public_flat_rd`, plus an `assign N = PATH;`.
/// - Force probe (`probe force N : T at PATH`): the same read-side
///   accessor, PLUS an `<N>_drv` + `<N>_en` pair annotated
///   `public_flat_rw`, plus an `always_comb` that procedurally
///   forces PATH from `<N>_drv` when `<N>_en` is high and releases
///   it otherwise. The HARC TB writes `<N>_drv` + `<N>_en` for
///   force; `release dut.<N>` lowers to just clearing `<N>_en`.
pub fn emit_stub(dut_type: &str, probes: &[Probe]) -> Result<String, String> {
    let mut out = String::new();
    writeln!(out, "// Generated by harc — do not edit.").ok();
    writeln!(out, "// SystemVerilog `bind` stub for HARC probe declarations").ok();
    writeln!(out, "// on `let dut : {dut_type}`. See docs/probe-signals.md.").ok();
    writeln!(out).ok();
    writeln!(out, "module __harc_probe_{dut_type};").ok();
    // Read-side declarations — one per probe, regardless of force.
    for p in probes {
        let decl = sv_type_decl(&p.ty)?;
        writeln!(
            out,
            "    logic{decl} {name} /* verilator public_flat_rd */;",
            name = p.name.name
        ).ok();
    }
    // Force-only drive + enable pair.
    for p in probes {
        if !p.force {
            continue;
        }
        let decl = sv_type_decl(&p.ty)?;
        writeln!(
            out,
            "    logic{decl} {name}_drv /* verilator public_flat_rw */;",
            name = p.name.name
        ).ok();
        writeln!(
            out,
            "    logic {name}_en  /* verilator public_flat_rw */;",
            name = p.name.name
        ).ok();
    }
    // Read-side continuous assigns. Targets are qualified with the
    // bound module's name (`<DutType>.<path>`) — Verilator's bind-scope
    // upward reference resolves unqualified sub-instance ports (e.g.
    // `alu0.a`) but trips on local `logic`s of the bound module
    // itself (e.g. `decode_rs1_val`). Qualifying with the module
    // name makes both cases resolve uniformly.
    for p in probes {
        writeln!(
            out,
            "    assign {name} = {dut_type}.{path};",
            name = p.name.name,
            path = p.path,
        ).ok();
    }
    // Force-side procedural drive. Targets are qualified with the
    // bound module's name (`<DutType>.<path>`) — Verilator needs the
    // fully-qualified reference inside the bind stub to resolve the
    // force/release target. Unqualified upward references work for
    // read-side `assign` but trip the optimizer for `force` because
    // the signal would otherwise be eliminated.
    for p in probes {
        if !p.force {
            continue;
        }
        writeln!(out, "    always_comb begin").ok();
        writeln!(out, "        if ({name}_en) begin", name = p.name.name).ok();
        writeln!(
            out,
            "            force {dut_type}.{path} = {name}_drv;",
            path = p.path,
            name = p.name.name,
        ).ok();
        writeln!(out, "        end else begin").ok();
        writeln!(out, "            release {dut_type}.{path};", path = p.path).ok();
        writeln!(out, "        end").ok();
        writeln!(out, "    end").ok();
    }
    writeln!(out, "endmodule").ok();
    writeln!(out).ok();
    writeln!(out, "bind {dut_type} __harc_probe_{dut_type} harc_probes ();").ok();
    Ok(out)
}

/// Mangled C++ accessor for a probe signal under `dut->rootp->...`.
/// Matches the Verilator 5.x encoding for instance/signal paths:
/// `<TopModule>__DOT__harc_probes__DOT__<signal>`.
pub fn mangled_accessor(dut_type: &str, probe_name: &str) -> String {
    format!("{dut_type}__DOT__harc_probes__DOT__{probe_name}")
}
